### ISSUE TITLE
[6.0] Version downgrade does not restore certificate image

### ISSUE THREAD

**Issue by santanamic** [gocodebox/lifterlms#2054] opened 2022-03-09 04:37 UTC
### Reproduction Steps

+ Upgrade to version 6

After updating to version 6 I realized that the certificate image is no longer a metafield to be the featured image of the post.

The problem is that when I go back to the old version that image is not there. In fact I can see that the `_llms_certificate_image` field was deleted when updating.

It would be interesting to maintain compatibility.

**Comment by eri-trabiccolo** [comment] 2022-03-09 09:13
@santanamic 
Thanks for reporting this.

I see what you mean, although the featured image of the post is a meta field: `_thumbnail_id`.

> The problem is that when I go back to the old version that image is not there. In fact I can see that the _llms_certificate_image field was deleted when updating.

This only happens with old certificates if you ran the DB update to migrate data to 6.0 (which is not automatic - it requires a button to be pressed), and for newly created certificates.
LifterLMS 6.0.0 is a major release, it introduces breaking changes to the API and requires a DB update - we use the semantic versioning, - a list of all the changes can be found in the [release notes](https://make.lifterlms.com/2022/03/08/lifterlms-version-6-0-0/).

> It would be interesting to maintain compatibility.

[Meta properties _llms_achievement_image and _llms_certificate_image have been moved to the meta property _thumbnail_id in order to utilize the WordPress core’s featured image functionality and internal APIs.](https://make.lifterlms.com/2022/03/08/lifterlms-version-6-0-0/#developernotes)

So in order to do what you're asking, we'd had to leave all the (now) unused metadata in the DB, in the remote case that a user would downgrade to a version pre 6.0 after having ran the DB update. 

This is working as expected. What you think @gocodebox/engineering ?

**Comment by pondermatic** [comment] 2022-03-09 12:48
If we were to support downgrading LifterLMS back to 5.x, we would need a "Downgrade Database" feature that unmigrated the database changes. While this is technically possible, I don't think we've ever offered the ability to downgrade. Have we ever had requests to downgrade before?

**Comment by thomasplevy** [comment] 2022-03-09 14:28
Hey @santanamic 

Thanks for upgrading and reaching out with this suggestion. Before we dig any deeper into what's happened here I'd like to note a few things on these changes that I think is relevant:

1) Moving to use featured image functionality as opposed to custom meta keys allows us (and other developers) to use WordPress core APIs and interfaces. This allows a learner codebase (less custom code) to provide functionality that already exists in WordPress
2) Other metadata that was migrated -- namely the template -> child relationship -- was moved for the similar reason as above but also to reduce reliance on the postmeta table. This later decision is a performance improvement.
3) All the data that was migrated was migrated in a way that integrations will continue to work if they reference the previous metadata but they *will* be met with deprecation warnings when doing so. This was done in order to allow anyone who doesn't have time to upgrade their code (or simply didn't realize what would happen) to continue using the old meta keys without any issues.

You can see all of that code here if you're interested: https://github.com/gocodebox/lifterlms/blob/trunk/includes/functions/llms-functions-deprecated.php#L185-L328

So while we have not provided a _downgrade_ routine to rollback the database to the previous version, we *have* maintained compatibility.

I feel it's also worth noting that all of these changes are _required_ on LifterLMS 6.0 moving forward, however, we won't be removing the backwards compatibility until the next major release. We don't have a timeline planned for this but it will likely be at least 3 months, more likely 6 - 12 months before we see a LifterLMS 7.0. When we do start working on 7.0 we will provide at least a 4 - 6 week beta period where we'll denote the removed functionality far in advance so you have time to address the changes that may need to be made. As an example, the first prerelease of LifterLMS 6.0 was published in [December](https://github.com/gocodebox/lifterlms/releases/tag/6.0.0-alpha.1). So there's no emergency here on your part to make any adjustments. The deprecation warnings are there to let you know what's changed and you can address that in whatever timeline you see fit. 

If you're seeing any issues with the backwards compatibility structure we've put in place could you please let us know and provide a bit more specific information on the problem(s) you're encountering after an upgrade?

Thanks!

**Comment by santanamic** [comment] 2022-03-09 15:43
Ok i can understand.

I suggest some changes in the database upgrade:

1 - Update must not remove legacy data from postmeta table or any other table.
2 - User should have the option to remove this legacy data. Let's call this 'Legacy Data Removal'. This option can be shown via notification in the WordPress dashboard. It would be important to point out that removing this data would make dowgrande unfeasible.

Thanks

**Comment by thomasplevy** [comment] 2022-03-09 15:54
@santanamic 

> 1 - Update must not remove legacy data from postmeta table or any other table.

Why not? Given that we added backwards compatibility functions so that the migrated (not removed) data is still accessible via the old meta keys why should our update *not* remove data?

> 2 - User should have the option to remove this legacy data. Let's call this 'Legacy Data Removal'. This option can be shown via notification in the WordPress dashboard. It would be important to point out that removing this data would make dowgrande unfeasible.

This is a different approach to a database migration but it's, essentially, the same thing as what we already did. The notification provides a link to the changes that will be made should you proceed and when clicking the button to perform a warning is displayed recommending a database migration.

---

I'm never opposed to improvements but the strategy we've implemented was worked through carefully. We've had the database migrations in place for several months in beta and less than 24 hour following release you're reporting that we *should change that strategy* without providing any real reason why.

At this point you're suggesting that we *rewrite our entire migration strategy* because.... why?

**Comment by santanamic** [comment] 2022-03-09 16:40
I have a custom addon. It adds a backside image to the certificate and some other merge codes. This will be broken in version 6. When this happens, users will try to revert to version 5.x... You can predict the problem.

I believe users could not be hostage to version 6.X.

> At this point you're suggesting that we rewrite our entire migration strategy because....why?

I think you're exaggerating when you say 'rewrite our entire migration strategy'. When developing your strategy, were there no concerns about maintaining compatibility with third-party add-ons?

> I'm never opposed to improvements but the strategy we've implemented was worked through carefully. We've had the database migrations in place for several months in beta and less than 24 hour following release you're reporting that we should change that strategy without providing any real reason why.

Please note that I only tried to help. If the problem presented here is not relevant to you, just close the topic.

Thanks

**Comment by thomasplevy** [comment] 2022-03-09 16:48
@santanamic 

I don't intend to be dismissive, but it's hard to approach a change without knowing what problem the change would solve. Now I understand -- you have code that isn't working correctly after release. Let's work on that problem.

> I think you're exaggerating when you say 'rewrite our entire migration strategy'. When developing your strategy, were there no concerns about maintaining compatibility with third-party add-ons?

A ton... And we addressed this by adding backwards compatiblity code that reroutes `get_post_meta()` requests to the migrated keys to their new location.

Are you accessing the metadata via `get_post_meta()` or are you accessing it directly via `$wpdb`?

If you're accessing the data via `get_post_meta()` there shouldn't be any immediate problems outside of deprecation warnings. 

If you're accessing the data directly via database calls I'd urge you to switch over to using the WordPress core metadata apis so that the backwards compatibility we put in place will work as intended.

If there's something else entirely going on that we could work to resolve would you consider providing more explicit details on the problem you're seeing and provide us with a copy of your add-on so we can recreate the issues and work to address it?


Thanks!

**Closed as completed** 2022-03-09 18:16 UTC
Labels: Status: Need Information
