### ISSUE TITLE
When cloning a course, should the date of the course be the cloned date or the same date the course was created?

### ISSUE THREAD

**Issue by toyinogun** [gocodebox/lifterlms#1433] opened 2020-11-17 08:37 UTC
Recreation steps:
Click clone on a course
You'll notice the date is the same as the cloned course

Suggested solution:
I feel the date should be that of the cloned date

For example, If I created a course on the 16th of November, and I clone the course today 17th, November the date should read 17th November and not 16th November.

HS-141043

**Comment by thomasplevy** [comment] 2020-11-17 15:37
I don't have any strong reason or argument for keeping it the way it is currently, however, whenever a change is made we must consider that there will be some amount of users who consider the change to be a bug or a regression.

What's the problem here?
Why can we not just say "This is the way it is and if you don't like it change the date immediately following cloning?"

**Comment by toyinogun** [comment] 2020-11-17 16:15
> What's the problem here?
Why can we not just say "This is the way it is and if you don't like it change the date immediately following cloning?"

It's not really a problem but ease of use. I feel it can be confusing if after cloning a course, you now see two courses with the same date. A user may not know how to check for the new/old one. As I said, not really a problem but I agree with the customer in this case that it may be better if the cloned date is automatically used instead of using the same date.

**Comment by toyinogun** [comment] 2020-11-18 08:31
@thomasplevy Another user asking the same clone question - HS-141456

**Comment by thomasplevy** [comment] 2020-11-18 15:58
@toyinogunseinde as the customer in the new ticket asked, they aren't complainig about the date, just asking if there's a way they can "identify the clone" -- the clone lesson functionality changes the copy to "Draft" and then appends "(Clone)" to the end. I'm thinking mimicing this behavior might be better than changing the date. I really don't know about changing the date but my feeling is that the date isn't actually the problem and we're pointing a finger at the date when there's actually a better solution out there.

@eri-trabiccolo thoughts on this?

**Comment by eri-trabiccolo** [comment] 2020-11-18 16:13
@thomasplevy 
I more inclined to the _draft_ status + `__( 'Clone', 'lifterlms' )` appended to the title as you say, rather than changing the published date, because it's a clone action, if it was a duplication one, would have made more sense.

btw:
Actually the _draft_ status should be already set, according to the [docs](https://lifterlms.com/docs/clone-lifterlms-course/):
_The page will reload and a duplicate copy of your course will be on the courses list marked as a draft._

**Comment by toyinogun** [comment] 2020-12-21 11:23
@eri-trabiccolo Can you try cloning a course to see if it marks as a draft? I just did and it did not so it's difficult to know which is cloned or not.

BTW, this customer is facing the same issue HS-145801

**Comment by eri-trabiccolo** [comment] 2020-12-21 11:45
@toyinogunseinde 
I never said the opposite, I said, that I'm more inclined to draft status + clone appended to the title, then I said _Actually the draft status should be already set_, but I was referring to what Thomas said, which made implicit the fact that, at the moment when cloning a course no "Clone" string is appended. See what Thomas says:



 _as the customer in the new ticket asked, they aren't complainig about the date, just asking if there's a way they can "identify the clone" -- the clone lesson functionality changes the copy to "Draft" and then appends "(Clone)" to the end. **I'm thinking mimicking this behavior might be better than changing the date**. I really don't know about changing the date but my feeling is that the date isn't actually the problem and we're pointing a finger at the date when there's actually a better solution out there_




So Thomas said that he wanted to mimic the lesson's behavior, implying that at the moment the course clone doesn't mimic it. So I said that I was agreeing with him, and added that it should have already been so, according to the documentition.
Sorry if what we took for granted caused confusione here, hope it's more clear now, let me know if otherwise.

**Comment by toyinogun** [comment] 2021-01-25 09:01
HS-151323 (3rd question)

**Closed as completed** 2021-01-26 19:25 UTC
Labels: Type: Enhancement, help wanted, Status: Has PR, good first issue, hacktoberfest, Severity: Low
