### ISSUE TITLE
if a course has a free access plan course enrollment restrictions are being ignored

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms#266] opened 2016-12-15 23:29 UTC
date restrictions should be factored into account here

### Recreation Steps

1. Create course with course start & end dates
2. Create a free access plan for the course
3. Student will be able to enroll into course outside of the start & end dates

### Expected

+ Student should not be able to enroll outside of those dates. 

---

The issue here *may* be with the free enrollment form at https://github.com/gocodebox/lifterlms/blob/master/templates/product/free-enroll-form.php

There's a validation issue -- some validation is happening in templates while some is happening in the form submission controller (https://github.com/gocodebox/lifterlms/blob/master/includes/controllers/class.llms.controller.orders.php#L168). Validation for orders in general (free or paid) should be validated in one place rather than being split between the controller and the template(s)

**Comment by thomasplevy** [comment] 2018-06-05 16:04
Setup recreation steps as I've forgotten exactly what this is

**Comment by thomasplevy** [comment] 2019-02-05 17:49
free access plan with course start / end dates are being ignored?

**Comment by toyinogunseinde** [comment] 2020-05-20 07:37
@thomasplevy @eri-trabiccolo I don't think this bug was fixed. I just created a free course locally and set the course end date to 18th May 2020.

I was still allowed to enroll for the course. I believe if the course end date has passed, it should remove the access plan block or even deactivate the access plan or something

**Comment by eri-trabiccolo** [comment] 2020-05-20 07:42
@toyinogunseinde according to the issue's labels: Type: Bug, Status: Can't Recreate
and the fact that this issue is still open I agree with you: this bug is not fixed.
I think that Thomas, as stated in his second comment, just forgot how to reproduce it, that's why he added Status: Can't Recreate.
Those are only my speculations of course :D

So yeah the issue should still be there.

**Comment by eri-trabiccolo** [comment] 2020-05-20 13:22
Toyin and I discussed about this, here's a summary of the status quo:
1) In the LifterLMS 3.38.0 changelog we can read:
"Fixed an issue causing free access plans to bypass course enrollment restrictions like capacity and enrollment time periods."
**enrollment restrictions**: **capacity and enrollment time periods** are the keys here.
As matter of fact that refers to the issue https://github.com/gocodebox/lifterlms/issues/1121, that it has been actually fixed.

2) About the HS-122205 ticket:
It was not clear whether or not the customer was still experiencing issues with the enrollment restrictions on free access plans OR with course dates (which are different concepts and settings). 

In the previous comment https://github.com/gocodebox/lifterlms/issues/266#issuecomment-631295666, Toyin was actually referring to the fact that you can still enroll a course even if the Course End Date is passed (course closed). This is true, I don't think it's a bug, and in any case this is valid even for non free access plans.

Anyway according to what Toyin tested, though, the customer's (staging) site is now showing this issue anymore.

### **Finally**
Now reading this the title of this very issue: 
_if a course has a free access plan **course enrollment restrictions** are being ignored_

I think this is a duplicate of #1121 (or better, the opposite), even if in the issue description we can read:
1. Create course with **course start & end dates**
3. Student will be able to enroll into **course outside of the start & end dates**
and that's a little bit misleading.

But as said above, if we're talking about course start and end dates I don't think this is a real bug - users can change the enrollment dates according to the course opening dates, if that's what they want.

So I'm going to close this (fixed by #1123).

Whoever thinks I'm wrong please:
1. say it quietly adding that I'm beautiful on the other hand
2. re-open this
3. motivate

Thanks!

**Closed by eri-trabiccolo** 2020-05-20 13:22 UTC
Labels: Severity: Normal, Type: Bug

**Comment by thomasplevy** [comment] 2020-05-20 15:05
> In the previous comment #266 (comment), Toyin was actually referring to the fact that you can still enroll a course even if the Course End Date is passed (course closed). This is true, I don't think it's a bug, and in any case this is valid even for non free access plans.

This is correct. This is the way it should work and it's not a bug.

Enrollment Dates and Course Dates (the time period when you are eligible to complete content) are two separate concepts with their own sets of restriction rules.

Ideally if you have a course which *ends* you'd want to setup enrollment dates to match that but you don't have to.

Perhaps we should have a discussion around whether or not the feature should be adjusted but it's *not technically a bug* because it's doing what it semantically should do -- __control access to content within a course__ - the enrollment dates control the enrollment period. Use them both and you're good to go.

**Comment by toyinogunseinde** [comment] 2020-05-20 15:52
Thanks for the clarification @thomasplevy and @eri-trabiccolo. I was obviously confused. Many thanks.
