### ISSUE TITLE
Dollar Signs Regardless of Currency

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1372] opened 2020-10-13 15:30 UTC
### Reproduction Steps

+ Change currency in LifterLMS Settings
+ Go to sales reporting screen
+ Look at the y axis of the graph

### Expected Behavior

+ the currency symbol should match the site

### Actual Behavior

+ it stays the dollar sign

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```


```

</details>

This issue has be recreated:
+ [X] Locally
+ [X] On a staging site
+ [X] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

HS-137401

**Comment by thomasplevy** [comment] 2020-10-13 16:28
Duplicate of #1096

**Closed as completed by thomasplevy** 2020-10-13 16:28 UTC
Labels: Type: Bug, Severity: Low
