### ISSUE TITLE
Completed column sorting does not work in the reports

### ISSUE THREAD

**Issue by toyinogun** [gocodebox/lifterlms#1529] opened 2021-02-15 15:20 UTC
### Reproduction Steps

Go to LifterLMS >> Reporting >> Courses >> Click on a course >> Students.

Then try sorting it by the completed date by clicking on the "completed" title.

### Expected Behavior

It should either change to ascending or descending sort

### Actual Behavior

Does not do anything. Stays the same.

### Error Messages / Logs

+ Include any relevant error messages or log files
```
N/A

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
N/A

```

</details>

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

HS-154928

**Comment by thomasplevy** [comment] 2021-02-15 16:09
Duplicate of #760

**Closed as completed** 2021-02-15 16:09 UTC
Labels: Type: Bug, Severity: Low
