### ISSUE TITLE
Reviewing Old Quizzes that have been changed causes critical error

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1102] opened 2020-04-14 11:06 UTC
### Reproduction Steps

+ Create a quiz
+ Take the quiz (as a student so it shows up in reporting)
+ Go back to quiz and remove a question or delete it.
+ Go into reporting to review the quiz for the student.
+ Attempt to save the review.

### Expected Behavior

+ the review saves

### Actual Behavior

+ it throws an error

### Error Messages / Logs

+ Include any relevant error messages or log files
```
An error of type E_ERROR was caused in line 263 of the file /home/starsh13/public_html/wp-content/plugins/lifterlms/includes/models/model.llms.quiz.attempt.question.php. Error message: Uncaught Error: Call to a member function get_auto_grade_type() on null in /home/starsh13/public_html/wp-content/plugins/lifterlms/includes/models/model.llms.quiz.attempt.question.php:263

Stack trace:

#0 /home/starsh13/public_html/wp-content/plugins/lifterlms/includes/models/model.llms.quiz.attempt.php(579): LLMS_Quiz_Attempt_Question->get_status()

#1 /home/starsh13/public_html/wp-content/plugins/lifterlms/includes/models/model.llms.quiz.attempt.php(127): LLMS_Quiz_Attempt->is_auto_gradeable()

#2 /home/starsh13/public_html/wp-content/plugins/lifterlms/includes/controllers/class.llms.controller.admin.quiz.attempts.php(112): LLMS_Quiz_Attempt->calculate_grade()

#3 /home/starsh13/public_html/wp-content/plugins/lifterlms/includes/controllers/class.llms.controller.admin.quiz.attempts.php(67): LLMS_Controller_Admin_Quiz_Attempts->save_grade(Object(LLMS_Quiz_Attempt))

#4 /home/starsh13/public_html/wp-includes/class-wp-hook.php(287): LLMS_Controller_Admin_Quiz_Attempts->maybe_run_actions('')

#5 /home/starsh13/public_
```
HS-117320

**Comment by thomasplevy** [comment] 2020-04-14 12:22
@nrherron92 this is a duplicate of #840

**Closed by thomasplevy** 2020-04-14 12:22 UTC
Labels: good first issue, help wanted, language: php, type: bug
