### ISSUE TITLE
Fatal Error in Dashboard Notifications for Manual Due Payment when Course is Deleted

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1723] opened 2021-08-02 15:11 UTC
### Reproduction Steps

+HS-172724

+ Create a course with repeating payments
+ Enable manual payments and purchase the course with manual payments
+ Make sure that the Basic notification for manual due payments is enabled
+ After the course is purchased trash and then permanently delete the course
+ Go back to the dashboard on the front end -> notifications

### Expected Behavior

+ The notifications would show as expected

### Actual Behavior

+ The merge code {{Product_Title}} for the Manual Payment Due basic notice causes a fatal error from the deleted course that is listed in the notifications

### Error Messages / Logs

+ Include any relevant error messages or log files
```
Fatal error: Uncaught Error: Call to a member function get_post_type_label() on null in /var/www/danskcoachakademi.dk/public_html/wp-content/plugins/lifterlms/includes/notifications/views/class.llms.notification.view.manual.payment.due.php:237 Stack trace: #0 /var/www/danskcoachakademi.dk/public_html/wp-content/plugins/lifterlms/includes/abstracts/llms.abstract.notification.view.php(611): LLMS_Notification_View_Manual_Payment_Due->set_merge_data('{{PRODUCT_TYPE}...') #1 /var/www/danskcoachakademi.dk/public_html/wp-content/plugins/lifterlms/includes/abstracts/llms.abstract.notification.view.php(680): LLMS_Abstract_Notification_View->get_merged_string('En betaling er ...') #2 /var/www/danskcoachakademi.dk/public_html/wp-content/plugins/lifterlms/includes/abstracts/llms.abstract.notification.view.php(260): LLMS_Abstract_Notification_View->get_title() #3 /var/www/danskcoachakademi.dk/public_html/wp-content/plugins/lifterlms/includes/abstracts/llms.abstract.notification.view.php(477): LLMS_Abstract_Notification_View->get_basic in /var/www/danskcoachakademi.dk/public_html/wp-content/plugins/lifterlms/includes/notifications/views/class.llms.notification.view.manual.payment.due.php on line 237


```

### System and Environment Information

<details>
<summary>System Report</summary>

```

Home Url: https://danskcoachakademi.dk
Site Url: https://danskcoachakademi.dk
Login Url: https://danskcoachakademi.dk/wp-login.php
Version: 5.8
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: da_DK
Multisite: No
Page For Posts: Blog (#46) [https://danskcoachakademi.dk/coach-academy-blog/]
Page On Front: Forside (#834) [https://danskcoachakademi.dk/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 5.1.2
Db Version: 5.1.2
Course Catalog: Uddannelser & Kurser (#15456) [https://danskcoachakademi.dk/uddannelser/]
Membership Catalog: Medlemskaber – Dansk Coach Akademi (#17124) [https://danskcoachakademi.dk/medlemskaber-dansk-coach-akademi/]
Student Dashboard: Kontrolpanel (#15459) [https://danskcoachakademi.dk/kontrolpanel/]
Checkout Page: Tilmelding (#15458) [https://danskcoachakademi.dk/tilmelding/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: -1
Membership Catalog Sorting: menu_order,ASC
Site Membership: Not Set
Courses Endpoint: mine-kurser
Edit Endpoint: revider-konto
Lost Password Endpoint: mistet-password
Vouchers Endpoint: find-rabatkupon
Autogenerate Username: no
Password Strength Meter: yes
Minimum Password Strength: medium
Terms Required: yes
Terms Page: Betingelser (#16885) [https://danskcoachakademi.dk/terms-conditions/]
Checkout Names: required
Checkout Address: optional
Checkout Phone: hidden
Checkout Email Confirmation: yes
Open Registration: no
Registration Names: required
Registration Address: hidden
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: yes
Account Names: required
Account Address: optional
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: yes
Country: DK
Currency: DKK
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: info@danskcoachakademi.dk
Email From Name: Dansk Coach Akademi
Email Footer Text:
Email Header Image: 16646
Cert Bg Width: 1193
Cert Bg Height: 794
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

PayPal: Enabled
PayPal Test Mode: Disabled
PayPal Logging: no
PayPal Order: 1
Stripe: Enabled
Stripe Test Mode: Disabled
Stripe Logging: no
Stripe Order: 1
Manuelt: Enabled
Manuelt Logging: no
Manuelt Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.34
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 1 GB
Php Memory Limit: 2048M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 300
Php Version: 7.4.22
Software: Apache
Wp Memory Limit: 2048M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15


Theme
-------------------------------------------

Name: Divi
Version: 4.9.10
Themeuri: http://www.elegantthemes.com/gallery/divi/
Authoruri: http://www.elegantthemes.com
Template:
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

All-in-One WP Migration: 7.45
All-in-One WP Migration Unlimited Extension: 2.42
bbPress: 2.6.6
Coming Soon Page, Maintenance Mode & Landing Pages by SeedProd: 6.6.0
Complianz - Terms and Conditions: 1.0.11
Complianz Privacy Suite (GDPR/CCPA) premium: 5.0.3
Duplicate Page: 4.4.1
Easy WP SMTP: 1.4.7
LifterLMS: 5.1.2
LifterLMS Helper: 3.3.1
LifterLMS Labs: 1.6.0
LifterLMS PayPal Gateway: 1.3.0
LifterLMS Social Learning: 1.4.0
LifterLMS Stripe Payment Gateway: 5.3.2
LiteSpeed Cache: 3.6.4
Loco Translate: 2.5.3
Monarch Plugin: 1.4.14
Really Simple SSL: 5.0.6
ShortPixel Image Optimizer: 4.22.3
Simple Local Avatars: 2.2.0
Wordfence Security: 7.5.4
WP GDPR Compliance: 1.5.6
WP Statistics: 13.0.9
Yoast SEO: 16.8
Yoast SEO Premium: 16.8


Integrations
-------------------------------------------

BbPress: Yes
BuddyPress: No
LifterLMS Social Learning: Yes


Template Overrides
-------------------------------------------
```

</details>

This issue has be recreated:
+ [X] Locally
+ [ ] On a staging site
+ [X] On a production website
+ [X] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by eri-trabiccolo** [comment] 2021-08-02 15:24
duplicate of https://github.com/gocodebox/lifterlms/issues/1463

**Closed as completed** 2021-08-02 15:25 UTC
