### ISSUE TITLE
Divi Update Broke Courses

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#2161] opened 2022-05-23 14:08 UTC
### Reproduction Steps

+ HS-193622
+ Install LifterLMS
+ Instal Divi
+ Make sure Courses are editable with builder
+ Try to open a course with the front end builder

### Expected Behavior

+ You can open the course and edit it

### Actual Behavior

+ There's a javascript error that blocks the course from loading in the builder

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->
react-dom.production.min.js?ver=16.12.0:112 TypeError: Cannot read properties of undefined (reading 'theme_builder_area')
    at bundle.js?ver=4.17.4:2:248311
    at Array.filter (<anonymous>)
    at Object.getSections (bundle.js?ver=4.17.4:2:248252)
    at Xe (bundle.js?ver=4.17.4:2:2254126)
    at t.getInitialState (bundle.js?ver=4.17.4:2:2256960)
    at new t (bundle.js?ver=4.17.4:2:2353536)
    at dh (react-dom.production.min.js?ver=16.12.0:69:276)
    at Bh (react-dom.production.min.js?ver=16.12.0:98:634)
    at Lj (react-dom.production.min.js?ver=16.12.0:231:293)
    at $h (react-dom.production.min.js?ver=16.12.0:137:227)
    at Fj (react-dom.production.min.js?ver=16.12.0:137:156)
    at We (react-dom.production.min.js?ver=16.12.0:132:26)
    at Ja (react-dom.production.min.js?ver=16.12.0:227:285)
    at sd (react-dom.production.min.js?ver=16.12.0:172:129)
    at react-dom.production.min.js?ver=16.12.0:174:803
    at Yh (react-dom.production.min.js?ver=16.12.0:132:463)
    at td (react-dom.production.min.js?ver=16.12.0:174:789)
    at Object.render (react-dom.production.min.js?ver=16.12.0:239:324)
    at bundle.js?ver=4.17.4:2:2231530
Re @ react-dom.production.min.js?ver=16.12.0:112
Oh.c.callback @ react-dom.production.min.js?ver=16.12.0:124
bh @ react-dom.production.min.js?ver=16.12.0:68
ah @ react-dom.production.min.js?ver=16.12.0:68
Pj @ react-dom.production.min.js?ver=16.12.0:159
unstable_runWithPriority @ react.production.min.js?ver=16.12.0:25
pb @ react-dom.production.min.js?ver=16.12.0:59
Ma @ react-dom.production.min.js?ver=16.12.0:151
We @ react-dom.production.min.js?ver=16.12.0:132
Ja @ react-dom.production.min.js?ver=16.12.0:227
sd @ react-dom.production.min.js?ver=16.12.0:172
(anonymous) @ react-dom.production.min.js?ver=16.12.0:174
Yh @ react-dom.production.min.js?ver=16.12.0:132
td @ react-dom.production.min.js?ver=16.12.0:174
render @ react-dom.production.min.js?ver=16.12.0:239
(anonymous) @ bundle.js?ver=4.17.4:2
Promise.then (async)
t @ bundle.js?ver=4.17.4:2
(anonymous) @ bundle.js?ver=4.17.4:2
i @ jquery.min.js?ver=3.6.0:2
dispatch @ jquery.min.js?ver=3.6.0:2
v.handle @ jquery.min.js?ver=3.6.0:2
(anonymous) @ boot.js?ver=4.17.4:1
load (async)
z @ VM2114:8
add @ jquery.min.js?ver=3.6.0:2
s.event.add @ jquery-migrate.min.js?ver=3.3.2:2
(anonymous) @ jquery.min.js?ver=3.6.0:2
each @ jquery.min.js?ver=3.6.0:2
each @ jquery.min.js?ver=3.6.0:2
Ee @ jquery.min.js?ver=3.6.0:2
on @ jquery.min.js?ver=3.6.0:2
bind @ jquery-migrate.min.js?ver=3.3.2:2
(anonymous) @ jquery.matchHeight.js?ver=0.7.0:376
(anonymous) @ jquery.matchHeight.js?ver=0.7.0:17
(anonymous) @ jquery.matchHeight.js?ver=0.7.0:19
bundle.js?ver=4.17.4:2 TypeError: Cannot read properties of undefined (reading 'theme_builder_area')
    at bundle.js?ver=4.17.4:2:248311
    at Array.filter (<anonymous>)
    at Object.getSections (bundle.js?ver=4.17.4:2:248252)
    at Xe (bundle.js?ver=4.17.4:2:2254126)
    at t.getInitialState (bundle.js?ver=4.17.4:2:2256960)
    at new t (bundle.js?ver=4.17.4:2:2353536)
    at dh (react-dom.production.min.js?ver=16.12.0:69:276)
    at Bh (react-dom.production.min.js?ver=16.12.0:98:634)
    at Lj (react-dom.production.min.js?ver=16.12.0:231:293)
    at $h (react-dom.production.min.js?ver=16.12.0:137:227)
    at Fj (react-dom.production.min.js?ver=16.12.0:137:156)
    at We (react-dom.production.min.js?ver=16.12.0:132:26)
    at Ja (react-dom.production.min.js?ver=16.12.0:227:285)
    at sd (react-dom.production.min.js?ver=16.12.0:172:129)
    at react-dom.production.min.js?ver=16.12.0:174:803
    at Yh (react-dom.production.min.js?ver=16.12.0:132:463)
    at td (react-dom.production.min.js?ver=16.12.0:174:789)
    at Object.render (react-dom.production.min.js?ver=16.12.0:239:324)
    at bundle.js?ver=4.17.4:2:2231530
(anonymous) @ bundle.js?ver=4.17.4:2
Promise.then (async)
t @ bundle.js?ver=4.17.4:2
(anonymous) @ bundle.js?ver=4.17.4:2
i @ jquery.min.js?ver=3.6.0:2
dispatch @ jquery.min.js?ver=3.6.0:2
v.handle @ jquery.min.js?ver=3.6.0:2
(anonymous) @ boot.js?ver=4.17.4:1
load (async)
z @ VM2114:8
add @ jquery.min.js?ver=3.6.0:2
s.event.add @ jquery-migrate.min.js?ver=3.3.2:2
(anonymous) @ jquery.min.js?ver=3.6.0:2
each @ jquery.min.js?ver=3.6.0:2
each @ jquery.min.js?ver=3.6.0:2
Ee @ jquery.min.js?ver=3.6.0:2
on @ jquery.min.js?ver=3.6.0:2
bind @ jquery-migrate.min.js?ver=3.3.2:2
(anonymous) @ jquery.matchHeight.js?ver=0.7.0:376
(anonymous) @ jquery.matchHeight.js?ver=0.7.0:17
(anonymous) @ jquery.matchHeight.js?ver=0.7.0:19
```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: [removed]/wp-login.php
Version: 5.9.3
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Home (#125) [[removed]/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.5.0
Db Version: 6.5.0
Course Catalog: Not Set
Membership Catalog: Not Set
Student Dashboard: My Account (#107) [[removed]/my-account/]
Checkout Page: Purchase (#106) [[removed]/purchase/]
Course Catalog Per Page: -1
Course Catalog Sorting: date,DESC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: no
Terms Page: Not Set
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: yes
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: no
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Disabled
Manual Logging: 
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.5.5
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 1000
Php Max Upload Size: 100 MB
Php Memory Limit: 1024M
Php Post Max Size: 100M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 120
Php Version: 7.4.28
Software: nginx/1.20.2
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36


Theme
-------------------------------------------

Name: Divi
Version: 4.17.4
Themeuri: http://www.elegantthemes.com/gallery/divi/
Authoruri: http://www.elegantthemes.com
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

LifterLMS: 6.5.0
LifterLMS Advanced Quizzes: 2.0.1
LifterLMS Advanced Videos: 1.0.0-beta.18
LifterLMS Labs: 1.6.0
LifterLMS PDFs: 2.1.0


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No
LifterLMS PDFs: Yes
Videos: Vimeo: No
Videos: Wistia: No
Videos: YouTube: Yes


Template Overrides
-------------------------------------------




```

</details>

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by eri-trabiccolo** [comment] 2022-05-23 16:27
I'm investigated into this but I cannot reproduce exactly the same error.
I see it happens on a Natalie testing website as well, but I can recreate it from scratch, at the moment :/.

**Comment by eri-trabiccolo** [comment] 2022-05-23 17:01
This is how I was able to reproduce it:
- create a course with a theme which is not Divi, create it with the block editor (default)
- switch to Divi
- **make sure Divi forces the classic editor** (Divi -> Theme Options -> Builder -> Enable Classic Editor - Enabled)
- edit the course and click on Edit it with Divi, then on Edit with the Divi Builder, which will take you to the front-end editor.
At this point the issue should appear as Natie said.

I still need to investigate more on this though.

**Comment by eri-trabiccolo** [comment] 2022-05-26 08:32
I'm having hard time in reproducing this issue constantly, plus when I'm able I don't know what's the issue, and how could I fix it. :(

**Comment by eri-trabiccolo** [comment] 2023-05-15 13:11
No news on this since ages. Closing it, can't reproduce

**Closed as completed by eri-trabiccolo** 2023-05-15 13:11 UTC
Labels: Type: Conflict
