### ISSUE TITLE
Backslashes in post content disappear on cloning

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#596] opened 2018-06-27 11:03 UTC
During json encoding, each backslash (`\`) converts into `\\` which during json decode here disappears:  https://github.com/gocodebox/lifterlms/blob/master/includes/class.llms.generator.php#L82. A detailed explanation can be found here: https://stackoverflow.com/a/32057601/1589999

So, we'd have to replace the code ain Line 82 above with the following to preserve backslashes:
```
    $raw = json_decode( str_replace( '\\', '\\\\', $raw ), true );
```

**Comment by actual-saurabh** [comment] 2018-07-06 13:38
This also affects data/content on builder so backslashes (and hence LaTex) don't work in courses, quizzes, etc: https://github.com/gocodebox/lifterlms/blob/master/includes/admin/class.llms.admin.builder.php#L362

**Comment by tlawork** [comment] 2018-10-18 01:10
Is this issue being actively worked?  I desperately need to be able to use LaTeX in Quizzes.

**Comment by actual-saurabh** [comment] 2018-10-18 12:35
@tlawork the ability to use backslashes in quizzes, etc has been separated out into #677 and a possible fix proposed in #678. This one only tracks the issues with cloning courses, henceforth. 

It will be tested, merged and released asap. However, you can still copy the changes into your installation to make this work right away: https://github.com/gocodebox/lifterlms/pull/678/files

**Comment by thomasplevy** [comment] 2018-11-16 17:07
Final solution may be to use @actual-saurabh's fix from PR #678 in combination with `nl2br()` to prevent line breaks from being broken.

**Comment by eri-trabiccolo** [comment] 2019-04-11 21:48
Hi there,
I' think I've found a reason for this and a solution.

The blackslash stripping happens when the various llms post types are "added" to the db, either when cloned or imported from a json:
After a `post model` has been inserted in the db, the` LLMS_Post_Model` `set()` method:
 is called several times to set some properties (and the content is one of them) calling the WordPress core function `wp_update_post`, and passing to it an array as first parameter.

Here's where the strip happen.

The `wp_update_post` fist param, as per the [WordPress documentation](https://developer.wordpress.org/reference/functions/wp_update_post/), when passed as an array, is expected to be escaped, hence escaping it with `wp_slash()` solves the issue.

There are several other places in the LLMS code where the `wp_update_post()` is used. Would be good to check whether or not an escaping is needed there too.

**Comment by thomasplevy** [comment] 2019-04-12 15:56
@actual-saurabh can you dig up original recreation steps for the initially reported issues so we can use those to see if @eri-trabiccolo PR #807 solves that initial issue.

I've just read through all the of the comments and related issues stemming from this one and unfortunately I cannot find a satisfactory set of stupid clear recreation steps to test against.

**Comment by eri-trabiccolo** [comment] 2019-04-12 17:21
Well actually I made some confusion yesterday (it was quite late here in Italy).
The thing is that the backslash strip happens on `wp_insert_post()`, and of course on `wp_update_post() `when passing an array, because it would then call the `wp_insert_post()` with a not escaped post array.
So my PR is relying on the fact that the `set()` method will be always called to update the `post_content` amending the previous strip because of the `wp_slash()` added.

So, for a more robust solution, the post array should be "wp slashed" before inserting the post as well. I'm going to update the PR.

**Comment by eri-trabiccolo** [comment] 2019-04-12 18:11
@thomasplevy about the recreation steps:
Wouldn't be enough cloning a course (or a lesson) with a backslash in the content? If not, then I didn't get the issue :)

Without #807 you should see that the backslashes are stripped from the clone course (lesson)'s content.
With #807 you should see backslashes preserved in the clone course (lesson)'s content.

**Comment by thomasplevy** [comment] 2019-04-12 19:33
> Wouldn't be enough cloning a course (or a lesson) with a backslash in the content? If not, then I didn't get the issue :)

We've discussed this issue for several months across several issues both in GitHub and in face-to-face meetings and slack conversations. @actual-saurabh has a solid handle on it and while I think these are the steps we need to take I want to make sure there's nothing I'm forgetting / missing.

**Comment by eri-trabiccolo** [comment] 2019-04-13 12:31
As far as I understand [this recent topic](https://wordpress.org/support/topic/losing-content-when-coverting-to-post-to-lesson/) is related to this issue, and I've tested it gets fixed with #807 as well.

**Comment by actual-saurabh** [comment] 2019-04-15 13:02
Wow! Sometimes you miss the obvious in the thick of things. The solution does make sense theoretically. I also tested this:

**Test 1: Lesson Content**

- [x] Added `C:\\System32\Keys\` text to a lesson.
- [x] Before applying the fix, the text turns to `C:System32Keys` on both cloning and export-import

![Screenshot 2019-04-15 at 5 59 32 PM](https://user-images.githubusercontent.com/1739834/56132741-6b3fd280-5fa8-11e9-8ff9-96110ae51684.png)

![Screenshot 2019-04-15 at 6 00 00 PM](https://user-images.githubusercontent.com/1739834/56132755-7266e080-5fa8-11e9-91b6-43ce0d98082e.png)

- [x] After applying the fix, the slashes are preserved in lesson.

**Comment by actual-saurabh** [comment] 2019-04-15 13:03
I also tested this for quizzes but with quizzes the issue also is that the shortcodes aren't parsed and the mathjax doesn't get applied to the equation because the content is loaded by ajax.

**Comment by eri-trabiccolo** [comment] 2019-04-15 13:14
@actual-saurabh how can I reproduce the quiz issue? I guess I have to clone a lesson which has a quiz with backslashes in it?

**Comment by actual-saurabh** [comment] 2019-04-15 14:05
@eri-trabiccolo Sorry, I didn't mention that I was testing for latex. Backslashes do work in quizzes, just latex doesn't. Nothing that you can do. We'd have to tackle that separately. (unless you'd like to take a stab at it, as well).

**Comment by eri-trabiccolo** [comment] 2019-04-15 14:34
I see, yeah I can take a look at it, if I got the issue, as soon as I can, but you know I've been already lucky once :)

**Comment by thomasplevy** [comment] 2019-04-15 20:12
@eri-trabiccolo & @actual-saurabh,

> Sorry, I didn't mention that I was testing for latex. Backslashes do work in quizzes, just latex doesn't. Nothing that you can do. We'd have to tackle that separately. (unless you'd like to take a stab at it, as well).

Is this being tracked in another issues separately? If not please open one @actual-saurabh 

I'm getting really lost on what's a latex issue and what's not... I've seen so many different and somewhat related issues and I want to make sure something isn't getting lost!

**Comment by eri-trabiccolo** [comment] 2019-04-16 07:59
I think I'm not getting what we mean with LaTeX here :D
Let me explain:
If I copy&paste some of [these LaTeX examples](http://www2.informatik.uni-freiburg.de/~frank/ENG/latex-course/latex-course-1/examples_en.html) into the Quiz description (or even in a question), and I save it, backslashes are:
1) stripped with the current LifterLMS stable
2) preserved with the #807 applied

But I guess @actual-saurabh is referring to something different as the LaTeX examples I used are nothing else than strings with backslashes, either or not wrapped in a `<pre/>` :D 

I also don't know what's the role of mathjax in this (are we talking about a plugin to use mathjax?), sorry :/

I guess I need more info in order to actually tackle this further issue (whether it'll be tracked separately or not).

**Closed** 2019-04-22 17:08 UTC
Labels: good first issue, hacktoberfest, language: php, type: bug
