### ISSUE TITLE
Odd Formatting on Student Dashboard for Courses if you're using Elementor Canvas and Kadence Theme

### ISSUE THREAD

**Issue by magicemilymiddleton** [gocodebox/lifterlms#2057] opened 2022-03-10 16:51 UTC
### Reproduction Steps

1. Install Kadence Theme, Elementor Plugin, LifterLMS plugin
2. Enroll in 3 courses
3. Visit the dashboard page
4. Edit your dashboard page in Elementor
5. Under the Elementor page settings, select 'Elementor Canvas' as your page layout
6. Check the dashboard and you should see the first course jumps to the second line

Video Demo
https://www.loom.com/share/6f7dd21f91ef40f7bbd89b68bacecd24

### Expected Behavior

The courses would all be in line as they usually are

### Actual Behavior

The first course jumps to the second line and leaves a white space where the first course should be

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: [removed]/wp-login.php
Version: 5.9.1
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Blog (#2029) [[removed]/blog/]
Page On Front: Home (#1015) [[removed]/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.0.0
Db Version: 6.0.0-rc.1
Course Catalog: Courses (#2202) [[removed]/courses/]
Membership Catalog: Membership Catalog (#2129) [[removed]/memberships/]
Student Dashboard: Dashboard (#2131) [[removed]/dashboard/]
Checkout Page: Purchase (#2130) [[removed]/purchase/]
Course Catalog Per Page: 30
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: no
Terms Page: Not Set
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: no
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

PayPal: Disabled
PayPal Test Mode: Disabled
PayPal Logging: 
PayPal Order: 1
Stripe: Enabled
Stripe Test Mode: Enabled
Stripe Logging: no
Stripe Order: 1
Manual: Enabled
Manual Logging: 
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.37
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 8.0.16
Software: Apache/2.4.52 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36


Theme
-------------------------------------------

Name: Kadence
Version: 1.1.14
Themeuri: https://www.kadencewp.com/kadence-theme/
Authoruri: https://www.kadencewp.com/
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

bbPress: 2.6.9
Elementor: 3.5.6
Embed Any Document: 2.7.1
Kadence Blocks – Gutenberg Blocks for Page Builder Features: 2.2.10
LifterLMS: 6.0.0
LifterLMS Advanced Quizzes: 2.0.0
LifterLMS Advanced Videos: 1.0.0-beta.17
LifterLMS Custom Fields: 2.0.2
LifterLMS Groups: 1.0.0-beta.18
LifterLMS MailChimp Add-on: 3.2.0
LifterLMS Ninja Forms: 1.1.1
LifterLMS PayPal Gateway: 1.3.0
LifterLMS PDFs: 1.0.0
LifterLMS Private Areas: 1.1.5
LifterLMS Social Learning: 1.4.0
LifterLMS Stripe Payment Gateway: 5.4.0
LifterLMS WooCommerce: 2.2.1
Ninja Forms: 3.6.7
User Switching: 1.5.8
WooCommerce: 6.3.0


Integrations
-------------------------------------------

BbPress: Yes
BuddyPress: No
LifterLMS Groups: Yes
LifterLMS Ninja Forms: Yes
WooCommerce: No
LifterLMS MailChimp: No
LifterLMS Private Areas: Yes
LifterLMS Social Learning: Yes
Videos: Vimeo: No
Videos: Wistia: Yes
Videos: YouTube: No


Template Overrides
-------------------------------------------

course/lesson-preview.php (ver: 5.7.0): /srv/users/manager/apps/lifterlms-6-docs-will/public/wp-content/themes/kadence/lifterlms/ (ver: 4.4.0)
course/syllabus.php (ver: 4.4.0): /srv/users/manager/apps/lifterlms-6-docs-will/public/wp-content/themes/kadence/lifterlms/ (ver: 4.4.0)



```

</details>

This issue has be recreated:
+ [ X] Locally
+ [ X] On a staging site
+ [ X] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by thomasplevy** [comment] 2022-03-10 23:52
@willmiddleton-lifterlms do you have this running on a myliftersite.com site that we can have a quick look at to expedite debugging?

**Comment by thomasplevy** [comment] 2022-03-14 15:35
@willmiddleton-lifterlms any update for us here?

**Comment by magicemilymiddleton** [comment] 2022-03-15 16:26
@thomasplevy oh yeah, sorry I check in here on my open tickets like once a week: **_lifterlms-6-docs-will_** that's myliftersite that it's on that site can be broken/tested with

**Comment by thomasplevy** [comment] 2022-03-15 16:37
@gocodebox/engineering can someone have a look at this site today and get me update on the cause here please?

**Comment by eri-trabiccolo** [comment] 2022-03-15 18:17
@thomasplevy 
So the thing is that Kadence adds these classes to our course loop ul wrapper:
`grid-cols grid-sm-col-2 grid-lg-col-3`
Kadence styles them using the grid system:
```css
@media screen and (min-width: 1025px) {
  .grid-lg-col-3 {
    grid-template-columns: repeat(3, minmax(0, 1fr));
  }
}
@media screen and (min-width: 576px) {
  .grid-sm-col-2 {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }
}
.grid-cols {
  display: grid;
  grid-template-columns: minmax(0, 1fr);
  -webkit-column-gap: 2.5rem;
  -moz-column-gap: 2.5rem;
  column-gap: 2.5rem;
  row-gap: 2.5rem;
}
```
this is not `compatible` with the fact that we display an empty "table" before our ul list wrapper:
```css
.llms-loop-list::before {
  content: " ";
  display: table;
}
```
that pseudo element, is a column of the grid :D

Kadence itself accounts for this problems on its pages, e.g. on the course catalog, with this rule:
```css
.site .grid-cols::before {
  display: none;
}
``` 
Where `.site` is the Kadence's main wrapper (it wraps the whole body content). From the Kadence's header.php:
```php
<body <?php body_class(); ?>>
<?php wp_body_open(); ?>
<?php
/**
 * Kadence before wrapper hook.
 */
do_action( 'kadence_before_wrapper' );
?>
<div id="wrapper" class="site">
```
But when the Elementor Canvas is used (see Will's reproduction steps) that `.site` wrapper isn't printed so their "safety" rule doesn't apply.

Not sure what to do here though:
a) we contact Kadence people and tell them about this
b) we add some CSS to prevent this issue with Kadence, like:
`.llms-loop-list.grid-cols::before { display: none }`
and similar.

**Comment by thomasplevy** [comment] 2022-03-15 18:40
@eri-trabiccolo conceivably switching over to flex cols (dropping the clearfix pseudo element) could fix this? Also rendering the matchHeight jquery plugin unnecessary, too, I think.

Would this introduce too many theme compat issues you think?

**Comment by eri-trabiccolo** [comment] 2022-03-15 18:57
@thomasplevy 
Yeah the flex cols would allow us to get rid of matchHeight (which is actually used in the pricing table too).

It might conceivably create an issue with some themes like astra and kadence that add custom classes to style the columns, but sooner or later we have to do this. Shall we go with a beta for this change?

**Comment by thomasplevy** [comment] 2022-03-16 12:19
@eri-trabiccolo I don't want to start another project that's going to require a major version increase right now and I also don't want to add compatibility code for a conflict involving a theme and another plugin.

Let's put the CSS snippet into the snippets repo and @willmiddleton-lifterlms could you write a doc on the known conflict so we have a place to point to (with the above explanation)

We can address this in the next major version but right now I don't want to mess with it.

**Comment by thomasplevy** [comment] 2022-03-16 12:20
Once the snippet & doc are created lets close this

**Comment by eri-trabiccolo** [comment] 2022-03-16 14:42
@willmiddleton-lifterlms here's the snippet: https://github.com/gocodebox/snippets/blob/trunk/theme-compatibility/llms-kadence-elementor_canvas-loop.css

**Comment by eri-trabiccolo** [comment] 2022-03-30 07:28
doc can be found here: https://lifterlms.com/docs/fix-for-known-conflict-lifterlms-kadence-theme-and-elementor-canvas-layout-on-student-dashboard/
closing this.

**Closed as completed by eri-trabiccolo** 2022-03-30 07:28 UTC
Labels: Type: Conflict, Status: Needs Documentation
