### ISSUE TITLE
Deleted Voucher code still works

### ISSUE THREAD

**Issue by toyinogunseinde** [gocodebox/lifterlms#1083] opened 2020-04-04 13:30 UTC
### Reproduction Steps

Create a voucher code in the orders tab.
Verify the code works.
Delete the ~code~ voucher *post* and try the code again.
It still works

### Expected Behavior

The code isn't expected to work since it's been deleted

### Actual Behavior

Code continues to work

### Error Messages / Logs

HS-116461

**Comment by eri-trabiccolo** [comment] 2020-04-06 17:25
@toyinogunseinde 
I don't seem to be able to reproduce this...
Are you deleting the code or the whole voucher?

Looks like the issue happens when deleting the voucher without deleting the codes.
Can you confirm?

Thanks

**Comment by toyinogunseinde** [comment] 2020-04-06 18:44
@eri-trabiccolo 
Yes, you're correct. This happens when the voucher is deleted without deleting the codes. Looks like it's still stored in the tables or something.

Thanks

**Comment by thomasplevy** [comment] 2020-04-07 23:15
@toyinogunseinde a fix is in the works, let the customer know we should have this resolved in the next 24-48 hours

**Closed** 2020-04-08 17:38 UTC
Labels: language: php, status: has-pr, type: bug
