### ISSUE TITLE
Genesis layouts on courses reverts to default when making changes

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#2059] opened 2022-03-10 18:09 UTC
### Reproduction Steps

+ HS-187447
+ I've reached out to StudioPress but we're still waiting to hear back about Magazine Pro...
+ LifterLMS + Genesis Theme + Genesis Sample Child theme + Genesis Pro
+ Create a course and add a Genesis Layout
+ Click onto a setting in the layout like columns and make a change like trying to create three columns

### Expected Behavior

+ Three columns appear

### Actual Behavior

+ The layout disappears back to the default course content

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: https://natalie-test-site.myliftersite.com
Site Url: https://natalie-test-site.myliftersite.com
Login Url: https://natalie-test-site.myliftersite.com/wp-login.php
Version: 5.9.1
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Homepage (#1398) [https://natalie-test-site.myliftersite.com/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.0.0
Db Version: 6.0.0
Course Catalog: Course Catalog (#35) [https://natalie-test-site.myliftersite.com/courses/]
Membership Catalog: Membership Catalog (#36) [https://natalie-test-site.myliftersite.com/memberships/]
Student Dashboard: Dashboard (#38) [https://natalie-test-site.myliftersite.com/dashboard/]
Checkout Page: Checkout (#715) [https://natalie-test-site.myliftersite.com/checkout/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: yes
Terms Page: Activate (#443) [https://natalie-test-site.myliftersite.com/activate/]
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: yes
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: team+sandbox@lifterlms.com
Email From Name: A LifterLMS Sandbox
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 1123
Cert Bg Height: 794
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Enabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.37
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 8.0.16
Software: Apache/2.4.52 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36


Theme
-------------------------------------------

Name: Genesis Sample
Version: 3.4.1
Themeuri: https://demo.studiopress.com/
Authoruri: https://www.studiopress.com/
Template: genesis
Child Theme: Yes
Llms Support: No


Plugins
-------------------------------------------

Genesis Blocks: 1.4.0
Genesis eNews Extended: 2.2.0
LifterLMS: 6.0.0
LifterLMS PDFs: 2.0.1
Simple Social Icons: 3.0.2
User Switching: 1.5.8
WP Mail Logging: 1.10.4
WP Rollback: 1.7.1


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No
LifterLMS PDFs: Yes


Template Overrides
-------------------------------------------




```

</details>

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by thomasplevy** [comment] 2022-03-10 23:50
@nrherron92 credentials in 1pass aren't working to debug this. Do you have a copy of this setup on a temp site we can review in the meantime?

**Comment by thomasplevy** [comment] 2022-03-10 23:51
I'm asking because I am COMPLETELY unfamiliar with Genesis (last time I truly worked with it in any serious capacity was like 2015) and I was hoping to kickstart debugging on an existing site instead of learning how to set all of this stuff up from scratch.

**Comment by thomasplevy** [comment] 2022-03-10 23:51
I also have no idea if I have a license to genesis somewhere

**Comment by nrherron92** [comment] 2022-03-11 15:05
@thomasplevy yes! sorry I had it set up for you on myliftersite in the system report, forgot I had that turned on for debug, and then started debugging something else. 

It's all set up here again: https://natalie-test-site.myliftersite.com/wp-admin/post.php?post=1444&action=edit 

If you drag the columns to be 3 instead that's a quick way to see it happen.

**Comment by eri-trabiccolo** [comment] 2022-03-14 17:52
I've investigated into this and:
1) the issue regards to the Advanced Columns block, and it happens when you change/set the columns number
2) that block is part of the [Genesis Blocks](https://wordpress.org/plugins/genesis-blocks/) plugin (free), and it happens with whatever theme
3) the issue happens also with a custom post type (not part of LifterLMS) which specifies a default template.

```php
add_action(
	'init',
	function() {
		register_post_type(
			'movies',
			array(
				'labels'       => array(
					'name'          => 'Movies',
					'singular_name' => 'Movie',
				),
				'public'       => true,
				'has_archive'  => true,
				'rewrite'      => array( 'slug' => 'movies' ),
				'show_in_rest' => true,
				'template'     => array(
					array(
						'core/heading',
						array(
							'content'   => 'Whatever',
							'level'     => 3,
							'textAlign' => 'center',
						),
					),
				),
			)
		);
	}
);

```
This is something they need to fix as it doesn't depend on something _weird_ we're doing (because we're not doing anything weird :D).
Started a new topic on wordpress.org forum: https://wordpress.org/support/topic/issue-with-advanced-columns-block-and-custom-post-type-with-block-template
Couldn't find a github repo for this very plugin.

@nrherron92 you can relay this information to the customer maybe?

**Comment by nrherron92** [comment] 2022-03-16 14:24
@eri-trabiccolo I let the user know and linked him to your topic!

**Comment by thomasplevy** [comment] 2022-03-16 14:36
I'm in favor of closing this as it's clearly not a bug in our side. Anyone opposed?

**Closed as completed** 2022-03-16 14:41 UTC
Labels: Type: Conflict, Severity: Normal
