### ISSUE TITLE
Drip Warning Does not display with BuddyBoss

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1069] opened 2020-03-23 10:52 UTC
### Reproduction Steps

Using BuddyBoss theme set up a course with prerequisites or drip settings. 
Go through the first course to mark complete and hit the prereq/drip setting where it bumps you to the main course page. There is no warning as expected for why the user is back on the main page. 

### Expected Behavior

There should be a standard LifterLMS warning that lets users know when they can access the course again.

### Actual Behavior

There is none.

HS-112186

**Comment by eri-trabiccolo** [comment] 2020-03-24 15:02
I tried to reproduce this with drip settings on a lesson, set to be "released" on a specific date.
It worked fine, cannot reproduce it locally mmm.

**Comment by thomasplevy** [comment] 2020-03-26 21:20
@nrherron92 is there anything more we can or should be doing here? i haven't actually taken a stab at recreating with buddyboss but I will if you want some more backup.

**Comment by thomasplevy** [comment] 2020-04-01 15:46
Closing this out as customer got help from BuddyBoss resolving the issue.

**Closed by thomasplevy** 2020-04-01 15:46 UTC
