### ISSUE TITLE
"Video Embed Error: Invalid URL!" is displayed on course pages even when featured video field is empty

### ISSUE THREAD

**Issue by rumspeed** [gocodebox/lifterlms#623] opened 2018-07-24 12:56 UTC
### 1. Reproduction Steps

In the Course Options under the General tab, if the Featured Video field is empty, LifterLMS will display the text "Video Embed Error: Invalid URL!" on the front end.

### 2. Expected Behavior

If the field is empty, it should not display anything on the front end.

**Comment by thomasplevy** [comment] 2018-07-24 15:37
@rumspeed I'm not able to reproduce this.

I tried to reproduce by adding spaces & tabs which may appear empty at a glance but are not actually empty but the white space is stripped and no video embed is attempted

The only way I can find a clear reproduction is to add something that isn't a valid URL (some gibberish like "astarst")

Can you confirm you're using the latest version of LifterLMS and can you also double check that this isn't an issue caused by a theme by switching to a default theme like twentyseventeen and by disabling all other plugins.

Thanks

**Comment by thomasplevy** [comment] 2018-07-24 15:37
@actual-saurabh If you have a free moment can you attempt reproduction as well and help ensure I'm not being overly dense

**Comment by thomasplevy** [comment] 2018-08-17 16:04
@rumspeed closing due to inability to recreate. Please answer the above questions if you'd like me to reopen.

**Closed by thomasplevy** 2018-08-17 16:04 UTC
Labels: can't recreate
