### ISSUE TITLE
Courses tab not shown in BuddyBoss Profile Navigation Customizer

### ISSUE THREAD

**Issue by pondermatic** [gocodebox/lifterlms#2142] opened 2022-05-03 19:26 UTC
### Reproduction Steps

+ Install LifterLMS 6.3.0 or 6.4.0.
+ Deactivate BuddyPress if installed. There is a faulty assumption about where a BuddyBoss class file is located.
+ Install BuddyBoss Platform plugin [2.0.0](https://github.com/buddyboss/buddyboss-platform/tree/2.0.0).
+ Ensure that LifterLMS --> Integrations --> BuddyPress is enabled and, in LifterLMS 6.3.0 and above, that "My Courses" is in the list of user profile endpoints.
+ Open Appearance --> Customize --> BuddyBoss Platform --> Profile Navigation

Brought up in slack chat. https://lifterlms.slack.com/archives/CCESQHE82/p1651256679255969

### Expected Behavior

![image](https://user-images.githubusercontent.com/5377968/166532432-1c789186-f799-484f-980b-b67a8760956e.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/5377968/166534985-79031a7e-87c8-49c6-abb5-925a5fbb6f39.png)

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

LifterLMS 6.2.0 (works), LifterLMS 6.3.0 and LifterLMS 6.4.0 (does not work)
BuddyBoss Platform 2.0.0
Astra theme
WordPress 5.9.1-src
PHP 8.0
Windows 10

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

**Comment by eri-trabiccolo** [comment] 2022-05-03 19:42
Sorry. I was actually aware of this and guiltly I haven't opened an issue.
Although I cannot fix this (that's an easy fix) until https://github.com/gocodebox/lifterlms/issues/2110  is fixed by BuddyBoss, otherwise we'll have a fatal (in the backend too).

**Comment by eri-trabiccolo** [comment] 2022-06-16 07:43
This is something we can fix now that #2110 is fixed.
Although the problem is that the fix would still generate a fatal for BuddyBoss customers who haven't updated to 2.0.3.
Shall we add a temporary `playnice` for bb<2.0.3? Alternatively I think we can write down some documentation with a filter to add to "disable" the fix.

**Comment by thomasplevy** [comment] 2022-06-16 15:25
@eri-trabiccolo can we conditionally add the fix only for the bb<2.0.3?

**Comment by eri-trabiccolo** [comment] 2022-06-16 16:37
@thomasplevy 
Well the thing is a bit different.
In https://github.com/gocodebox/lifterlms/pull/1816 we improved the BuddyPress (hence BuddyBoss) profile tabs integration but I also introduced a regression: https://github.com/gocodebox/lifterlms/pull/1816/files#diff-834d9c037e672d63bff32294a7f741a0871d7cc8e22fd33a25eb799d0ee5be15R129-R134
I basically _decided_ to limit the nav item addition to the user profile context, but the "addition" is also needed in admin context so that those nav items can be seen/managed in the customizer (or in Appearance->Menu).

So the whole thing is:
I need to fix this regression for ALL except for BuddyBoss<2.0.3 where fixing the regression will cause a PHP Fatal, because of their bug.

**Comment by thomasplevy** [comment] 2022-06-16 16:44
What is your `playnice` suggestion in that case @eri-trabiccolo ?

**Comment by eri-trabiccolo** [comment] 2022-06-16 17:07
That in the playnice class I add some code that checks the buddyboss version, and if less than 2.0.3 I "disable" the nav items addition in the "admin" context only. So users can still leverage the workaround described here:
https://github.com/gocodebox/lifterlms/issues/2110#issuecomment-1097715674

> @nrherron92 another workaround to avoid this is to change the View Courses endpoint slug in LifterLMS > Settings > Account to something different than my-courses

**Comment by thomasplevy** [comment] 2022-06-16 17:13
Alright that sounds good to me

**Closed as completed** 2022-07-12 19:56 UTC
Labels: Status: Has PR, Type: Conflict, Severity: Normal
