### ISSUE TITLE
Merge codes on certificates don't work when part of a reusable block

### ISSUE THREAD

**Issue by magicemilymiddleton** [gocodebox/lifterlms#2058] opened 2022-03-10 17:04 UTC
### Reproduction Steps

1. Install LifterLMS
2. Make a certificate
3. Add a merge code
4. Add your merge code to a reusable block
5. View your certificate and it should display the merge code instead of what data the merge code should grab

video reproduction:
https://www.loom.com/share/ebf99da1642e4bf0b082e2b4b875f651

### Expected Behavior

The content the merge code should show would show up

### Actual Behavior

The acutal brackets show up {current_date}

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```

Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: [removed]/wp-login.php
Version: 5.9.1
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Blog (#2029) [[removed]/blog/]
Page On Front: Home (#1015) [[removed]/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.0.0
Db Version: 6.0.0-rc.1
Course Catalog: Courses (#2202) [[removed]/courses/]
Membership Catalog: Membership Catalog (#2129) [[removed]/memberships/]
Student Dashboard: Dashboard (#2131) [[removed]/dashboard/]
Checkout Page: Purchase (#2130) [[removed]/purchase/]
Course Catalog Per Page: 30
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: no
Terms Page: Not Set
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: no
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Enabled
Manual Logging: 
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.37
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 8.0.16
Software: Apache/2.4.52 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36


Theme
-------------------------------------------

Name: Kadence
Version: 1.1.14
Themeuri: https://www.kadencewp.com/kadence-theme/
Authoruri: https://www.kadencewp.com/
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

LifterLMS: 6.0.0


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------

course/lesson-preview.php (ver: 5.7.0): /srv/users/manager/apps/lifterlms-6-docs-will/public/wp-content/themes/kadence/lifterlms/ (ver: 4.4.0)
course/syllabus.php (ver: 4.4.0): /srv/users/manager/apps/lifterlms-6-docs-will/public/wp-content/themes/kadence/lifterlms/ (ver: 4.4.0)


```

</details>

This issue has be recreated:
+ [ ] Locally
+ [ X] On a staging site
+ [ X] On a production website
+ [ X] With only LifterLMS and a default theme

**Comment by thomasplevy** [comment] 2022-03-10 23:46
Alright...

Resuable blocks are stored as a reference in the post's content, eg:

```html
<!-- wp:block {"ref":468} /-->
```

Other blocks are stored literally (the content in the post's content:

```html
<!-- wp:paragraph -->
<p>No. {sequential_id}</p>
<!-- /wp:paragraph -->
```

When we merge data into the merge codes we do a literal find and replace on the merge strings. So... when we find and replace against a resuable block the merge code is nowhere to be found.

---

We can handle this at "runtime" for certificates (probably adding a filter on [render_block](https://developer.wordpress.org/reference/hooks/render_block/) to run merging against any reusable block found within a certificate template post.

By this I mean: when we display (preview) a certificate template on the front end we can merge the reusable block data in that way

---

We can't do the same for awarded certificates without breaking the concept that *merge codes are not stored in awarded certificates*. The data is merged and then saved. So `{sequential_id}` or `{first_name}` is never saved in the content of an awarded cert (save for unpublished drafts). 

If we allow reusable blocks to be used on awarded certificates we'll have to merge them at runtime and then merge codes will technically be stored in the post's content and the content stored in the database will not be the actual content of the certificate, it will be a "template" of sorts that is only fully complete when merged at "runtime" (or display time).

---

I see a few options:

1) Block the usage of reusable blocks on certificates (templates and awarded)

This doesn't seem completely unacceptable to me because they *are* already templates. Perhaps people will want to create a standard certificate footer or something though.

2) Allow reusable blocks to be used but disallow merge codes within reusable blocks.

This will be technically difficult to implement though. There's no real API we could leverage to validate this. Perhaps we could roll our own that would pop a warning when merge codes are detected within a reusable block. But it would be a heavy solution...

3) Allow merge codes to be used on templates only (block them on awards) and then "explode" the resuable block into its non-reusable equivalent.

In this scenario we'd merge resuable blocks at runtime on templates (described above) and then when creating an awarded certificate we'd explode that resuable blocks into actual blocks before merging so the mergecodes could be present and actually merged.

---

Thoughts @gocodebox/engineering @gocodebox/success ??

---

@willmiddleton-lifterlms could you let me know if this is something you happened upon or if we already have a user leveraging this functionality?

**Comment by eri-trabiccolo** [comment] 2022-03-11 13:27
I'm missing something here...

> We can't do the same for awarded certificates without breaking the concept that merge codes are not stored in awarded certificates. The data is merged and then saved. So {sequential_id} or {first_name} is never saved in the content of an awarded cert (save for unpublished drafts).
> 
> If we allow reusable blocks to be used on awarded certificates we'll have to merge them at runtime and then merge codes will technically be stored in the post's content and the content stored in the database will not be the actual content of the certificate, it will be a "template" of sorts that is only fully complete when merged at "runtime" (or display time).

At the moment we can use merge codes in awards, and they are not exploded until the award is published. This means that for drafts and scheduled awards `{first_name}` is stored in the award's content as it is.
When this draft or scheduled award becomes `published` then the merge codes are exploded and saved with their values: `{first_name}` becomes `{Dude}`.

Can't we use the same approach then for reusable blocks?

**Comment by thomasplevy** [comment] 2022-03-11 16:05
@eri-trabiccolo we *could* but the problem is the content of the reusable block *is not stored* in the post's content. If we merge the data into the reusable block's content on publish then merge that data into *all the certificates that use that reusable block*

**Comment by eri-trabiccolo** [comment] 2022-03-11 16:23
Oh no sorry, I meant that when publishing the reusable block becomes "static" . Meaning that I was basically quoting:

> In this scenario we'd merge resuable blocks at runtime on templates (described above) and then when creating an awarded certificate we'd explode that resuable blocks into actual blocks before merging so the mergecodes could be present and actually merged.

And we do that when an awards is published (or when syncing and and the awards is already published).
Doesn't make sense?

**Comment by thomasplevy** [comment] 2022-03-11 16:27
@eri-trabiccolo oh... yea I see what you mean.

So yea we could:

Allow ~merge codes~ reusable blocks to be used on certificates

For templates, we can merge the data on the frontend during runtime/display
For awards we make the reusable blocks static and then merge / save into the post content.

Users could then add a reusable block to an awarded certificate directly and on publish / award (or save for an already-published award) it would automatically convert to static (and then merge) -- the merging already

I think this is the solution then. Yes?

**Comment by thomasplevy** [comment] 2022-03-11 16:28
The problem with this is that if creators are *expecting* the resuable block to be able to be changed they *cannot do it*. EG: it becomes detached from the reusable block. Realistically we should be advising users *not to use reusable blocks in awarded certs* and instead use them in the templates only. They can manage the content of the awarded certs from the template in favor of trying to use reusable blocks as a secondary or alternate templating system for certificates

**Comment by eri-trabiccolo** [comment] 2022-03-11 16:37
> The problem with this is that if creators are expecting the resuable block to be able to be changed they cannot do it. EG: it becomes detached from the reusable block. 

Yeah, I think we can just inform them that, like it happens with the merge codes, reusable blocks, convert to static `values` when the awards are published. 
Does it make sense?
Like ok you can use them, but that's the rule.

**Comment by thomasplevy** [comment] 2022-03-11 16:41
Seems fair, I agree.

@gocodebox/success any other thoughts? @chrisbadgett ?

**Comment by pondermatic** [comment] 2022-03-11 19:16
I agree. Dynamic on the template. Static on the award.

**Comment by magicemilymiddleton** [comment] 2022-03-15 16:24
@thomasplevy I ran into this while fixing an issue for a client, but haven't heard anyone else bring it up

**Comment by chrisbadgett** [comment] 2022-03-16 14:54
Dynamic on the template and static on the award sounds like a fair tradeoff.

**Closed as completed** 2022-04-19 17:29 UTC
Labels: Type: Bug, Status: Has PR
