### ISSUE TITLE
Problem on GlotPress

### ISSUE THREAD

**Issue by AndreaBarghigiani** [gocodebox/lifterlms#232] opened 2016-10-12 17:01 UTC
Hi there,
I want a report a strange behavior happened on translate.wordpress.org

I've tested several string and it seems that is affected only few string but I think is good to point it out. 

When I click on the References section, just to see where the string is used inside the code, I get a Trac error as showed in this image:

![schermata 2016-10-12 alle 18 25 51](https://cloud.githubusercontent.com/assets/190159/19319648/0fd5de74-90ae-11e6-937a-7d06feb72ecb.png)

At the moment I've seen this error only apperar on the string reletad to the action and as you can see GlotPress is trying to reach the version 2.7.12. I believe that this string didn't exist then but is only my assumption.

Hope this can help.

Keep up your amazing work guys!

**Comment by thomasplevy** [comment] 2016-10-12 17:56
@AndreaBarghigiani we're you translating the string "Action Group" when this occurred?

I think the issue is that I've included the vendor directory in the pot file and there is a different text domain in there which should be handled by a different language pack

I'll get a patch out with 3.0.1 to exclude the vendor directory from future .pot files

**Comment by thomasplevy** [comment] 2016-10-12 18:00
Actually.... I don't think that's the issue...

On closer look GlotPress is looking for a string in an old version which was never there in that old version --- eg the tag you're looking at there was never in 2.7.12 but the link is still looking for it....

I need to get on meta-i18n in slack and investigate further

ill keep you posted

**Comment by thomasplevy** [comment] 2016-10-12 22:53
@AndreaBarghigiani checked with GlotPress devs on Slack and they manually re-imported LifterLMS to GlotPress and said they weren't sure what happened or why but the issue has gone away

closing this out and thanks for catching it

also turns out I already had us ignoring the vendor directory but glotpress grabs everything translateable regardless of the pot

**Closed by thomasplevy** 2016-10-12 22:53 UTC
Labels: bug
