### ISSUE TITLE
Untranslatable strings

### ISSUE THREAD

**Issue by parfilov** [gocodebox/lifterlms#1110] opened 2020-04-17 18:53 UTC
Hello! I’m Lifter LMS Russian PTE. There are some untranslatable strings in the plugin and here I want to place some of them. Please don’t close this issue for some time while I’m working at translation. I’ll post strings when I’ll find them.

**Comment by parfilov** [comment] 2020-04-17 18:55
The first part is Catalog & Search Visibility options.

**Strings**
- Catalog & Search Visibility
- Visible
- Catalog Visibility
- Visible in the catalog and search results.
- Catalog only
- Only visible in the catalog.
- Search only
- Only visible in search results.
- Hidden
- Hidden from catalog and search results.

**Comment by parfilov** [comment] 2020-04-17 18:56
Enrollment Visibility settings.

**Strings**
- Enrollment Visibility
- Display to
- everyone
- enrolled users
- non-enrolled users or visitors
- logged in users
- logged out users

**Comment by parfilov** [comment] 2020-04-17 18:57
Coupon Settings General tab doesn't inherit the translation.

**Comment by parfilov** [comment] 2020-04-17 20:48
Coupon General Settings

**String**
When checked, the coupon can apply a discount to an access plan's "Trial Price"

**Comment by thomasplevy** [comment] 2020-04-17 21:42
A great deal of this is resulting from a complete lack of localization in [lifterlms-blocks](https://github.com/gocodebox/lifterlms-blocks). Historically this stems from having developed blocks very quickly since we kept hearing that the block editor was going to be delayed months and months and then we all collectively realized that Matt was not having any of that and it shipped on time surprising us internally (and globally, I think). At the time I didn't have time to finish a lot of things and due to the nature of our team and project and capacity issues I simply never got back to it and (somehow) no one has bugged us about it until today so we haven't actually fixed the known issue: https://github.com/gocodebox/lifterlms-blocks/issues/3

> The first part is Catalog & Search Visibility options.
> 
> **Strings**
> 
> * Catalog & Search Visibility
> * Visible
> * Catalog Visibility
> * Visible in the catalog and search results.
> * Catalog only
> * Only visible in the catalog.
> * Search only
> * Only visible in search results.
> * Hidden
> * Hidden from catalog and search results.

Can you confirm that these are all seen in the block editor options?

> Enrollment Visibility settings.
> 
> **Strings**
> 
> * Enrollment Visibility
> * Display to
> * everyone
> * enrolled users
> * non-enrolled users or visitors
> * logged in users
> * logged out users

This, too, are part of the block editor, yes?

**Comment by thomasplevy** [comment] 2020-04-17 21:47
@parfilov I've moved the confirmed issues to other independent issues. "Epic" issues with multiple issues across various files and codebases gets hard to track! If you see other strings or issues could you open new issues for them instead of posting them as comments on this one epic thread? WE'll get to all of them (I promise) and I don't actually care how many issues there are or you open I just want to ensure we can internally track them!

Thanks for your help as a contributor and for reporting these issues to us. i18n is important but often we miss small details since we're rarely actually loading translations ourselves. We rely on our users and contributors to help us find these oversights. Thanks you! <3

**Comment by parfilov** [comment] 2020-04-17 22:40
@thomasplevy [this](https://github.com/gocodebox/lifterlms/issues/1110#issuecomment-615409076) strings are not a part of blocks 
Here they are.
<img width="660" alt="Catalog   Search Visibility" src="https://user-images.githubusercontent.com/12493645/79619437-25fb3700-810d-11ea-8bcc-baeff9b916ef.png">

**Comment by parfilov** [comment] 2020-04-17 22:42
@thomasplevy and [this](https://github.com/gocodebox/lifterlms/issues/1110#issuecomment-615409484) strings are here:
<img width="660" alt="Enrollment Visibility" src="https://user-images.githubusercontent.com/12493645/79619533-770b2b00-810d-11ea-9a8e-dc45f8912727.png">

**Comment by parfilov** [comment] 2020-04-17 22:45
> @parfilov I've moved the confirmed issues to other independent issues. "Epic" issues with multiple issues across various files and codebases gets hard to track! If you see other strings or issues could you open new issues for them instead of posting them as comments on this one epic thread? WE'll get to all of them (I promise) and I don't actually care how many issues there are or you open I just want to ensure we can internally track them!
> 
> Thanks for your help as a contributor and for reporting these issues to us. i18n is important but often we miss small details since we're rarely actually loading translations ourselves. We rely on our users and contributors to help us find these oversights. Thanks you! <3

Ok. I'll try to create 1 issue for 1 string or strings group.

**Comment by thomasplevy** [comment] 2020-04-17 23:19
@parfilov 

Well yes, you're right, these are not in "blocks" but it's all rendered via JS in the block editor so it suffers from the lack of localization identified by gocodebox/lifterlms-blocks#3

I'm going to close this particular issue in favor of that existing issue.

Thanks for your reports and if you find anything else let us know.

Best,

**Closed** 2020-04-17 23:20 UTC
