### ISSUE TITLE
Parse error with the latest version of Redux plugin

### ISSUE THREAD

**Issue by toyinogun** [gocodebox/lifterlms#1611] opened 2021-04-27 09:53 UTC
### Reproduction Steps

Install the plugin: https://wordpress.org/plugins/redux-framework/
Try to go to the course builder of a course
You'll see this "200 Parse error" and some icons not appearing as shown in the screenshot:
![image](https://user-images.githubusercontent.com/62220599/116221647-b703e580-a745-11eb-9e82-f700811b24a3.png)

However, if you downgrade the plugin to a version lower(4.1.24), you won't get the Parse error anymore but the icons would still not appear.

### Expected Behavior

I don't expect the parsing error issue and the icons should appear

### Actual Behavior

Parsing error issue and icons don't appear

### Error Messages / Logs

+ Include any relevant error messages or log files
```
![image](https://user-images.githubusercontent.com/62220599/116222543-98521e80-a746-11eb-8f35-8114b915db91.png)
JQMIGRATE: Migrate is installed, version 3.3.2
load-scripts.php?c=1&load[chunk_0]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=5.7.1:2 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://lucky-rice.myliftersite.com/wp-content/plugins/redux-framework/redux-templates/assets/fonts/fa-solid-900.woff2
post_api.js:132 ContentDispatcherService: no listeners for an event URLS_SAFE_CHECK__STATUS_UPDATED
DevTools failed to load SourceMap: Could not load content for chrome-extension://liecbddmkiiihnedobmlmillhodjkdmb/js/content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://liecbddmkiiihnedobmlmillhodjkdmb/js/intercom-link-expand-loader.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
admin.php?page=llms-course-builder&course_id=972:1 Unchecked runtime.lastError: The message port closed before a response was received.
admin.php?page=llms-course-builder&course_id=972:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://cdn.loom.com/assets/fonts/circular/CircularXXWeb-Book-cd7d2bcec649b1243839a15d5eb8f0a3.woff2
2DevTools failed to load SourceMap: Could not load content for chrome-extension://liecbddmkiiihnedobmlmillhodjkdmb/js/intercom-link-expand-loader.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
post_api.js:132 ContentDispatcherService: no listeners for an event URLS_SAFE_CHECK__STATUS_UPDATED
post_api.js:132 ContentDispatcherService: no listeners for an event URLS_SAFE_CHECK__STATUS_UPDATED
content.js:657 ContentDispatcherService: no listeners for an event URLS_SAFE_CHECK__STATUS_UPDATED
post_api.js:132 ContentDispatcherService: no listeners for an event URLS_SAFE_CHECK__STATUS_UPDATED
safecheck.js:132 ContentDispatcherService: no listeners for an event URLS_SAFE_CHECK__STATUS_UPDATED
post_api.js:132 ContentDispatcherService: no listeners for an event URLS_SAFE_CHECK__STATUS_UPDATED
post_api.js:132 ContentDispatcherService: no listeners for an event URLS_SAFE_CHECK__STATUS_UPDATED
post_api.js:132 ContentDispatcherService: no listeners for an event URLS_SAFE_CHECK__STATUS_UPDATED
content.js:657 ContentDispatcherService: no listeners for an event URLS_SAFE_CHECK__STATUS_UPDATED
safecheck.js:132 ContentDispatcherService: no listeners for an event URLS_SAFE_CHECK__STATUS_UPDATED
```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: https://lucky-rice.myliftersite.com
Site Url: https://lucky-rice.myliftersite.com
Login Url: https://lucky-rice.myliftersite.com/wp-login.php
Version: 5.7.1
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Home (#889) [https://lucky-rice.myliftersite.com/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 4.21.0
Db Version: 4.21.0
Course Catalog: Courses (#245) [https://lucky-rice.myliftersite.com/courses-2/]
Membership Catalog: Membership Catalog (#6) [https://lucky-rice.myliftersite.com/memberships/]
Student Dashboard: Dashboard (#8) [https://lucky-rice.myliftersite.com/dashboard/]
Checkout Page: Purchase (#7) [https://lucky-rice.myliftersite.com/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: monthly-journeys
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: yes
Minimum Password Strength: strong
Terms Required: yes
Terms Page: Not Set
Checkout Names: required
Checkout Address: required
Checkout Phone: optional
Checkout Email Confirmation: yes
Open Registration: yes
Registration Names: required
Registration Address: hidden
Registration Phone: hidden
Registration Voucher: hidden
Registration Email Confirmation: yes
Account Names: required
Account Address: required
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: team+sandbox@lifterlms.com
Email From Name: A LifterLMS Sandbox
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Stripe: Enabled
Stripe Test Mode: Enabled
Stripe Logging: yes
Stripe Order: 0
PayPal: Enabled
PayPal Test Mode: Enabled
PayPal Logging: yes
PayPal Order: 1
Manual: Disabled
Manual Logging: 
Manual Order: 2


Server
-------------------------------------------

Mysql Version: 5.7.33
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 7.3.27
Software: Apache/2.4.46 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36


Theme
-------------------------------------------

Name: BuddyBoss Child
Version: 1.0.0
Themeuri: https://www.buddyboss.com/
Authoruri: https://www.buddyboss.com/
Template: buddyboss-theme
Child Theme: Yes
Llms Support: No


Plugins
-------------------------------------------

Beaver Builder Plugin (Pro Version): 2.4.2.2
Beaver Themer: 1.3.3.1
Classic Editor: 1.6
Code Snippets: 2.14.1
Gravity Forms: 2.4.24
Gravity Forms User Registration Add-On: 4.7
LifterLMS: 4.21.0
LifterLMS Advanced Quizzes: 1.1.1
LifterLMS Advanced Videos: 1.0.0-beta.14
LifterLMS Assignments: 1.1.12
LifterLMS Gravity Forms: 2.1.1
LifterLMS Groups: 1.0.0-beta.10
LifterLMS Helper: 3.0.2
LifterLMS Labs: 1.5.3
LifterLMS PayPal Gateway: 1.3.0
LifterLMS Private Areas: 1.1.2
LifterLMS Stripe Payment Gateway: 5.3.2
Loco Translate: 2.5.2
PublishPress Capabilities: 2.0
Query Monitor: 3.6.7
Rank Math SEO: 1.0.62
Redux: 4.1.26
WooCommerce: 5.2.2
WP Fusion: 3.37.11
WP Rollback: 1.7.1
Zapier for WordPress: 1.0.2


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No
LifterLMS Groups: Yes
LifterLMS Gravity Forms: No
LifterLMS Private Areas: Yes
Videos: Vimeo: Yes
Videos: Wistia: No
Videos: YouTube: Yes


Template Overrides
-------------------------------------------

content-certificate.php (ver: 4.21.0): /srv/users/manager/apps/lucky-rice/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.18.0)
achievements/loop.php (ver: 3.14.0): /srv/users/manager/apps/lucky-rice/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
achievements/template.php (ver: 3.14.6): /srv/users/manager/apps/lucky-rice/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.6)
certificates/loop.php (ver: 3.14.0): /srv/users/manager/apps/lucky-rice/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
certificates/preview.php (ver: 3.14.0): /srv/users/manager/apps/lucky-rice/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
course/author.php (ver: 4.11.0): /srv/users/manager/apps/lucky-rice/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.25.0)
course/lesson-preview.php (ver: 4.4.0): /srv/users/manager/apps/lucky-rice/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.19.2)
course/syllabus.php (ver: 4.4.0): /srv/users/manager/apps/lucky-rice/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.24.0)
loop/author.php (ver: 3.0.0): /srv/users/manager/apps/lucky-rice/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.0.0)
loop/content.php (ver: 3.14.0): /srv/users/manager/apps/lucky-rice/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
loop/featured-image.php (ver: 3.35.0): /srv/users/manager/apps/lucky-rice/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.35.0)
myaccount/dashboard-section.php (ver: 3.30.1): /srv/users/manager/apps/lucky-rice/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.30.1)
myaccount/header.php (ver: 3.14.0): /srv/users/manager/apps/lucky-rice/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.14.0)
myaccount/my-grades-single-table.php (ver: 3.24.0): /srv/users/manager/apps/lucky-rice/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.24.0)
myaccount/my-notifications.php (ver: 3.30.3): /srv/users/manager/apps/lucky-rice/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.30.3)
myaccount/my-orders.php (ver: 3.17.6): /srv/users/manager/apps/lucky-rice/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.17.6)
myaccount/view-order.php (ver: 3.35.0): /srv/users/manager/apps/lucky-rice/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.35.0)
product/access-plan-pricing.php (ver: 3.29.0): /srv/users/manager/apps/lucky-rice/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.29.0)
quiz/results-attempt-questions-list.php (ver: 3.17.8): /srv/users/manager/apps/lucky-rice/public/wp-content/themes/buddyboss-theme/lifterlms/ (ver: 3.17.8)



```

</details>

This issue has be recreated:
+ [ ] Locally
+ [ ] On a staging site
+ [ ] On a production website
+ [ ] With only LifterLMS and a default theme

HS-164540

**Comment by eri-trabiccolo** [comment] 2021-04-27 10:19
@toyinogunseinde 
thanks! this is basically a duplicate of #1610 (although your title is far more descriptive).
Please also note that switching to the manual saving, as said [here](https://github.com/gocodebox/lifterlms/issues/1610#issuecomment-826798244) and [here](https://github.com/gocodebox/lifterlms/issues/1610#issuecomment-827003690) avoids this issue as well (you might want to inform the customer about this).
Also an issue on the Redux Framework plugin repository has been opened: 
https://github.com/reduxframework/redux-framework-4/issues/215

p.s. 
I'm not able to reproduce the missing icons issue. It might depend on some other plugins. Redux Framework uses Font Awesome 5 and that should explain the issue (which is similar to https://github.com/gocodebox/lifterlms/issues/1563) but our style should override it - at least it does it locally.

**Closed as completed by eri-trabiccolo** 2021-04-27 10:19 UTC
Labels: Type: Conflict, Severity: Low, Status: Has Alternative

**Comment by kprovance** [comment] 2021-06-16 06:17
Actually, Redux does not use FA.  It uses Elusive icons.

**Comment by eri-trabiccolo** [comment] 2021-06-16 09:48
@kprovance the Redux Framework does use font awesome, at least in admin, as far as I can see:

https://plugins.trac.wordpress.org/browser/redux-framework/trunk/redux-templates/assets/fonts
https://plugins.trac.wordpress.org/browser/redux-framework/trunk/redux-templates/assets/css
https://plugins.trac.wordpress.org/browser/redux-framework/trunk/redux-templates/assets/css/admin.min.css
