### ISSUE TITLE
Hundreds of Student Welcome Emails Sending to User

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#2404] opened 2023-03-28 19:34 UTC
### Reproduction Steps

+ HS-215197
+ HS-215185
+ HS-215180
+ I have not been able to replicate this issue myself, but three independent users have reported it
+ Essentially, a user signs up to their site and the student welcome email sends hundreds of times
+ The only thing they all have in common is the LifterLMS Core, Astra theme, and Astra Pro plugin
+ None are on the same host. 
+ I'm getting credentials to the sites and will update once those are provided.

### Expected Behavior

+ student welcome only sends once

### Actual Behavior

+ email sends hundreds of times

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```


```

</details>

This issue has be recreated:
+ [ ] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by nrherron92** [comment] 2023-03-28 19:37
HS-215185 -- credentials in one pass, debug log was on during the event.

**Comment by nrherron92** [comment] 2023-03-28 19:54
HS-215197 -- credentials in one pass

**Comment by eri-trabiccolo** [comment] 2023-03-29 07:58
HS-215223
 HS-215215

**Comment by nrherron92** [comment] 2023-03-29 13:55
HS-213888

**Comment by eri-trabiccolo** [comment] 2023-03-31 07:04
This ended up being an issue generated by the Astra Pro plugin and resolved in their version [4.1.2](https://wpastra.com/changelog/astra-pro-4-1-2/): 
>Backward managing cron run into infinite loop which exhausted CPU usage on server.

I was not able to reproduce the issue locally, but I directly tested the version 4.1.2.
The customers who updated to 4.1.2 confirmed the issue to be resolved.

Gonna close this issue then, anyone feel free to re-open this.

**Closed as completed by eri-trabiccolo** 2023-03-31 07:04 UTC
Labels: Type: Conflict, Severity: High
