### ISSUE TITLE
Course Information Settings Move

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#2174] opened 2022-06-06 15:18 UTC
### Reproduction Steps

+ Courses -> Add New
+ The Course Length and Difficulty fields are visible under Course Options -> General
+ Save the course then view on the front end.
+ Jump back into edit the course, and now the Course Length field is now missing in Course Options > General and moved to the Course Information block where it belongs 

### Expected Behavior

+ It should always be under the Course Information block settings?

### Actual Behavior

+ It seems like the setting disappears from the user's view

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: https://dizzy-dust.myliftersite.com
Site Url: https://dizzy-dust.myliftersite.com
Login Url: https://dizzy-dust.myliftersite.com/wp-login.php
Version: 6.0
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Not Set
Permalink Structure: /%postname%/
Show On Front: posts
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.6.0
Db Version: 
Course Catalog: Course Catalog (#13) [https://dizzy-dust.myliftersite.com/courses/]
Membership Catalog: Membership Catalog (#14) [https://dizzy-dust.myliftersite.com/memberships/]
Student Dashboard: Dashboard (#16) [https://dizzy-dust.myliftersite.com/dashboard/]
Checkout Page: Purchase (#15) [https://dizzy-dust.myliftersite.com/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: no
Terms Page: Not Set
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: no
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: team+sandbox@lifterlms.com
Email From Name: A LifterLMS Sandbox
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 
Cert Bg Height: 
Cert Legacy Compat: 


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Disabled
Manual Logging: 
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.38
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 8.0.19
Software: Apache/2.4.53 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36


Theme
-------------------------------------------

Name: Twenty Twenty-Two
Version: 1.2
Themeuri: https://wordpress.org/themes/twentytwentytwo/
Authoruri: https://wordpress.org/
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

LifterLMS: 6.6.0


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------




```

</details>

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by thomasplevy** [comment] 2022-06-06 15:54
The block appears in both places to accommodate usage of the classic editor (plugin) for courses. There's a regression somewhere in the logic that hides the field when the block editor is being used. I'm guessing something has changed in a block-editor related core API to cause the checks to not run in the order they used to. Or, possibly, this has always worked this way and we haven't noticed it.

Either way, the field should only display in the metabox when the classic editor is being used.

**Comment by thomasplevy** [comment] 2022-06-06 15:55
@nrherron92 i'm marking this low severity and moving to the backlog because it's relatively minor and I don't see a related user issue. Even if there is a user issue I think confirming the bug and explaining the expected behavior should be satisfactory to the user. If you feel differently let me know.

**Comment by actuallyakash** [comment] 2023-04-05 13:13
Fixed in https://github.com/gocodebox/lifterlms-blocks/pull/189

**Closed as completed** 2023-04-25 15:39 UTC
Labels: Type: Bug, Status: Has PR, Severity: Low
