### ISSUE TITLE
PHP 8 Fatal Error With Forms

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#2066] opened 2022-03-16 18:19 UTC
### Reproduction Steps

+ HS-189149
+ PHP must be on PHP 8
+ Turn on Custom Fields
+ Go  into edit the checkout form and add a checkbox field then save
+ Go into your profile and check one of the boxes and save your profile
+ Go into a course and create a free access plan
+ View the course.

### Expected Behavior

+ everything functions as normal

### Actual Behavior

+ there's a fatal error on the access plan

### Error Messages / Logs

+ Include any relevant error messages or log files
```
Fatal error: Uncaught TypeError: strip_tags(): Argument #1 ($string) must be of type string, array given in /srv/users/manager/apps/natalie-test-site/public/wp-includes/formatting.php:5374 Stack trace: #0 /srv/users/manager/apps/natalie-test-site/public/wp-includes/formatting.php(5374): strip_tags(Array) #1 /srv/users/manager/apps/natalie-test-site/public/wp-content/plugins/lifterlms/includes/forms/class-llms-form-field.php(384): wp_strip_all_tags(Array) #2 /srv/users/manager/apps/natalie-test-site/public/wp-content/plugins/lifterlms/includes/forms/class-llms-form-field.php(341): LLMS_Form_Field->get_html_attributes(Array) #3 /srv/users/manager/apps/natalie-test-site/public/wp-content/plugins/lifterlms/includes/forms/class-llms-form-field.php(452): LLMS_Form_Field->get_field_html() #4 /srv/users/manager/apps/natalie-test-site/public/wp-content/plugins/lifterlms/includes/functions/llms-functions-forms.php(42): LLMS_Form_Field->get_html() #5 /srv/users/manager/apps/natalie-test-site/public/wp-content/plugins/lifterlms/includes/forms/class-llms-forms.php(750): llms_form_field(Object(LLMS_Form_Field), false) #6 /srv/users/manager/apps/natalie-test-site/public/wp-content/plugins/lifterlms/templates/product/free-enroll-form.php(27): LLMS_Forms->get_free_enroll_form_html(Object(LLMS_Access_Plan)) #7 /srv/users/manager/apps/natalie-test-site/public/wp-content/plugins/lifterlms/includes/functions/llms.functions.template.php(120): include('/srv/users/mana...') #8 /srv/users/manager/apps/natalie-test-site/public/wp-content/plugins/lifterlms/templates/product/access-plan-button.php(26): llms_get_template('product/free-en...', Array) #9 /srv/users/manager/apps/natalie-test-site/public/wp-content/plugins/lifterlms/includes/functions/llms.functions.template.php(120): include('/srv/users/mana...') #10 /srv/users/manager/apps/natalie-test-site/public/wp-content/plugins/lifterlms/includes/functions/llms.functions.templates.pricing.table.php(64): llms_get_template('product/access-...', Array) #11 /srv/users/manager/apps/natalie-test-site/public/wp-includes/class-wp-hook.php(307): llms_template_access_plan_button(Object(LLMS_Access_Plan)) #12 /srv/users/manager/apps/natalie-test-site/public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array) #13 /srv/users/manager/apps/natalie-test-site/public/wp-includes/plugin.php(474): WP_Hook->do_action(Array) #14 /srv/users/manager/apps/natalie-test-site/public/wp-content/plugins/lifterlms/templates/product/access-plan.php(48): do_action('llms_acces_plan...', Object(LLMS_Access_Plan)) #15 /srv/users/manager/apps/natalie-test-site/public/wp-content/plugins/lifterlms/includes/functions/llms.functions.template.php(120): include('/srv/users/mana...') #16 /srv/users/manager/apps/natalie-test-site/public/wp-content/plugins/lifterlms/includes/functions/llms.functions.templates.pricing.table.php(47): llms_get_template('product/access-...', Array) #17 /srv/users/manager/apps/natalie-test-site/public/wp-includes/class-wp-hook.php(307): llms_template_access_plan(Object(LLMS_Access_Plan)) #18 /srv/users/manager/apps/natalie-test-site/public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array) #19 /srv/users/manager/apps/natalie-test-site/public/wp-includes/plugin.php(474): WP_Hook->do_action(Array) #20 /srv/users/manager/apps/natalie-test-site/public/wp-content/plugins/lifterlms/templates/product/pricing-table.php(61): do_action('llms_access_pla...', Object(LLMS_Access_Plan)) #21 /srv/users/manager/apps/natalie-test-site/public/wp-content/plugins/lifterlms/includes/functions/llms.functions.template.php(120): include('/srv/users/mana...') #22 /srv/users/manager/apps/natalie-test-site/public/wp-content/plugins/lifterlms/includes/functions/llms.functions.templates.pricing.table.php(231): llms_get_template('product/pricing...', Array) #23 /srv/users/manager/apps/natalie-test-site/public/wp-content/plugins/lifterlms/libraries/lifterlms-blocks/includes/blocks/class-llms-blocks-pricing-table-block.php(104): lifterlms_template_pricing_table(1460) #24 /srv/users/manager/apps/natalie-test-site/public/wp-includes/class-wp-hook.php(309): LLMS_Blocks_Pricing_Table_Block->output(Array) #25 /srv/users/manager/apps/natalie-test-site/public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array) #26 /srv/users/manager/apps/natalie-test-site/public/wp-includes/plugin.php(474): WP_Hook->do_action(Array) #27 /srv/users/manager/apps/natalie-test-site/public/wp-content/plugins/lifterlms/libraries/lifterlms-blocks/includes/class-llms-blocks-abstract-block.php(151): do_action('llms_pricing-ta...', Array, '') #28 /srv/users/manager/apps/natalie-test-site/public/wp-includes/class-wp-block.php(255): LLMS_Blocks_Abstract_Block->render_callback(Array, '', Object(WP_Block)) #29 /srv/users/manager/apps/natalie-test-site/public/wp-includes/blocks.php(883): WP_Block->render() #30 /srv/users/manager/apps/natalie-test-site/public/wp-includes/blocks.php(921): render_block(Array) #31 /srv/users/manager/apps/natalie-test-site/public/wp-includes/class-wp-hook.php(307): do_blocks('<!-- wp:html {"...') #32 /srv/users/manager/apps/natalie-test-site/public/wp-includes/plugin.php(189): WP_Hook->apply_filters('<!-- wp:html {"...', Array) #33 /srv/users/manager/apps/natalie-test-site/public/wp-includes/post-template.php(253): apply_filters('the_content', '<!-- wp:html {"...') #34 /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/astra/template-parts/single/single-layout.php(43): the_content() #35 /srv/users/manager/apps/natalie-test-site/public/wp-includes/template.php(772): require('/srv/users/mana...') #36 /srv/users/manager/apps/natalie-test-site/public/wp-includes/template.php(716): load_template('/srv/users/mana...', false, Array) #37 /srv/users/manager/apps/natalie-test-site/public/wp-includes/general-template.php(204): locate_template(Array, true, false, Array) #38 /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/astra/inc/template-parts.php(264): get_template_part('template-parts/...') #39 /srv/users/manager/apps/natalie-test-site/public/wp-includes/class-wp-hook.php(307): astra_entry_content_single_template('') #40 /srv/users/manager/apps/natalie-test-site/public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array) #41 /srv/users/manager/apps/natalie-test-site/public/wp-includes/plugin.php(474): WP_Hook->do_action(Array) #42 /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/astra/inc/core/theme-hooks.php(443): do_action('astra_entry_con...') #43 /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/astra/template-parts/content-single.php(29): astra_entry_content_single() #44 /srv/users/manager/apps/natalie-test-site/public/wp-includes/template.php(772): require('/srv/users/mana...') #45 /srv/users/manager/apps/natalie-test-site/public/wp-includes/template.php(716): load_template('/srv/users/mana...', false, Array) #46 /srv/users/manager/apps/natalie-test-site/public/wp-includes/general-template.php(204): locate_template(Array, true, false, Array) #47 /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/astra/inc/class-astra-loop.php(120): get_template_part('template-parts/...', 'single') #48 /srv/users/manager/apps/natalie-test-site/public/wp-includes/class-wp-hook.php(307): Astra_Loop->template_parts_post('') #49 /srv/users/manager/apps/natalie-test-site/public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array) #50 /srv/users/manager/apps/natalie-test-site/public/wp-includes/plugin.php(474): WP_Hook->do_action(Array) #51 /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/astra/inc/class-astra-loop.php(199): do_action('astra_template_...') #52 /srv/users/manager/apps/natalie-test-site/public/wp-includes/class-wp-hook.php(307): Astra_Loop->loop_markup('') #53 /srv/users/manager/apps/natalie-test-site/public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array) #54 /srv/users/manager/apps/natalie-test-site/public/wp-includes/plugin.php(474): WP_Hook->do_action(Array) #55 /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/astra/inc/core/theme-hooks.php(258): do_action('astra_content_l...') #56 /srv/users/manager/apps/natalie-test-site/public/wp-content/themes/astra/single.php(27): astra_content_loop() #57 /srv/users/manager/apps/natalie-test-site/public/wp-includes/template-loader.php(106): include('/srv/users/mana...') #58 /srv/users/manager/apps/natalie-test-site/public/wp-blog-header.php(19): require_once('/srv/users/mana...') #59 /srv/users/manager/apps/natalie-test-site/public/index.php(17): require('/srv/users/mana...') #60 {main} thrown in /srv/users/manager/apps/natalie-test-site/public/wp-includes/formatting.php on line 5374

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
afc.pr

Admin Credentials

Email: help@lifterlms.com
Password: https://onetimesecret.com/secret/931dv0vtmqw1v6hdvdj9i6lfxl7ccjk

System Report

Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: [removed]/wp-login.php
Version: 5.9.2
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Inicio (#16) [[removed]/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.0.0
Db Version: 6.0.0
Course Catalog: Not Set
Membership Catalog: Membership Catalog (#7756) [[removed]/memberships/]
Student Dashboard: Mi cuenta (#8092) [[removed]/mi-cuenta/]
Checkout Page: Orden de Compra (#7757) [[removed]/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: date,DESC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: no
Minimum Password Strength: medium
Terms Required: yes
Terms Page: Términos y Condiciones (#254) [[removed]/terminos-y-condiciones/]
Checkout Names: required
Checkout Address: required
Checkout Phone: required
Checkout Email Confirmation: yes
Open Registration: no
Registration Names: required
Registration Address: required
Registration Phone: required
Registration Voucher: required
Registration Email Confirmation: yes
Account Names: required
Account Address: required
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: PR
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text:
Email Header Image:
Cert Bg Width: 792
Cert Bg Height: 612
Cert Legacy Compat: yes


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

PayPal: Enabled
PayPal Test Mode: Disabled
PayPal Logging: no
PayPal Order: 1
Stripe: Enabled
Stripe Test Mode: Disabled
Stripe Logging: no
Stripe Order: 1
Manual: Enabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 10.3.34
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 2 GB
Php Memory Limit: 1028M
Php Post Max Size: 2048M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 600
Php Version: 8.0.16
Software: Apache
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36


Theme
-------------------------------------------

Name: AFC-LMS
Version: 2.5
Themeuri:
Authoruri: https://www.afc.pr
Template: Divi
Child Theme: Yes
Llms Support: No


Plugins
-------------------------------------------

Add Admin CSS: 2.0.1
Akismet Anti-Spam: 4.2.2
Attachment Pages Redirect: 1.1.2
Better Search: 3.0.3
Bloom: 1.3.12
Custom Body Class: 0.7.2
Data Tables Generator by Supsystic: 1.10.14
Display PHP Version: 1.7
Ditty (formerly Ditty News Ticker): 3.0.16
Divi DotNav: 1.4.7
Divi Overlays: 2.9.6.6
Divi Supreme Pro: 4.8.37
Facebook Chat Plugin - Live Chat Plugin for WordPress: 2.3
Facebook for WordPress: 3.0.6
FileBird: 4.4
Gutenberg: 12.7.2
HM Multiple Roles: 1.6
Jetpack: 10.7
LifterLMS: 6.0.0
LifterLMS Advanced Quizzes: 2.0.1
LifterLMS Advanced Videos: 1.0.0-beta.18
LifterLMS Custom Fields: 2.0.2
LifterLMS Helper: 3.4.1
LifterLMS Labs: 1.6.0
LifterLMS PayPal Gateway: 1.3.0
LifterLMS PDFs: 2.0.1
LifterLMS Private Areas: 1.1.5
LifterLMS Stripe Payment Gateway: 5.4.0
Logo Carousel Pro: 3.4.1
Password Protect WordPress Lite: 1.8.1
PDF Poster PRO: 1.5
Post Type Search Module For Divi: 1.2.1
Really Simple SSL: 5.3.0
Really Simple SSL pro: 5.3.4
Safe SVG: 1.9.10
Simple Iframe: 1.1.1
Social Warfare: 4.3.0
Supreme Modules Lite - Divi Theme, Extra Theme and Divi Builder: 2.4.1
User Profile Picture: 2.6.0
W3 Total Cache: 2.2.1
Wordfence Security: 7.5.8
WP Last Modified Info: 1.7.7
WP Mail SMTP: 3.3.0
WP Sitemap Page: 1.9.1
WP STAGING: 2.9.6
Zoom WordPress Plugin: 4.23.1


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No
LifterLMS PDFs: Yes
LifterLMS Private Areas: Yes
Videos: Vimeo: Yes
Videos: Wistia: No
Videos: YouTube: Yes


Template Overrides
-------------------------------------------

course/lesson-preview.php (ver: 5.7.0): /home/asesorf7/public_html/afcpr/wp-content/themes/afc-lms7/lifterlms/ (ver: 5.7.0)
product/access-plan-pricing.php (ver: 3.29.0): /home/asesorf7/public_html/afcpr/wp-content/themes/afc-lms7/lifterlms/ (ver: 3.29.0)

```

</details>

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by pondermatic** [comment] 2022-03-16 22:39
At first, I was unable to reproduce the issue because of an extra checkout form on my site. After deleting it, I can confirm that this is a bug.

- [ ] `LLMS_Form_Field::get_html_attributes()` should prevent passing an array to `wp_strip_all_tags()`.

@gocodebox/engineering, Should checkboxes in checkout forms be displayed on the free enroll form? If yes, then should the value be serialized if it's an array?

**Comment by eri-trabiccolo** [comment] 2022-03-17 12:39
@pondermatic 
> Should checkboxes in checkout forms be displayed on the free enroll form?
I guess so.
> If yes, then should the value be serialized if it's an array?
I guess we can serialize it as long as we then are able to unserialize it when creating the order.

The problem is that we build the free enroll form from the checkout form by turning all the fields into hidden type fields:
https://github.com/gocodebox/lifterlms/blob/dev/includes/forms/class-llms-forms.php#L700-L703

But we have some field types (`checkbox` and `radio`) that are allowed to be array and that we treat differently here:
https://github.com/gocodebox/lifterlms/blob/dev/includes/forms/class-llms-form-field.php#L266-L311
and here:
https://github.com/gocodebox/lifterlms/blob/dev/includes/forms/class-llms-form-field.php#L375-L377

So alternatively we can rework the way we create that "hidden" form...

**Comment by pondermatic** [comment] 2022-03-29 18:48
@nrherron92, this issue is fixed in the next release of LifterLMS.

**Closed as completed** 2022-03-30 18:52 UTC
Labels: Type: Bug, Status: Has PR
