### ISSUE TITLE
LifterLMS does not respect WordPress Dashboard > Users > Profile > Personal Options > Language when Loco Translate is used.

### ISSUE THREAD

**Issue by dominiquemariano** [gocodebox/lifterlms#2459] opened 2023-06-12 10:01 UTC
### Reproduction Steps
Watch [this video](https://share.getcloudapp.com/geuPYZy1) I recorded.

### Expected Behavior
LifterLMS should respect the language set in `WordPress Dashboard > Users > Profile > Personal Options > Language`.

### Actual Behavior
LifteLMS only respects the language set in `WordPress Dashboard > Settings > General > General Settings > Site Language`.

This issue has been recreated:
+ [x] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

**Comment by eri-trabiccolo** [comment] 2023-06-12 10:08
How this is related to Loco Translate?

Is this a duplicate of the following?
https://github.com/gocodebox/lifterlms/issues/2324

**Comment by dominiquemariano** [comment] 2023-06-12 10:12
> How this is related to Loco Translate?
> 
> Is this a duplicate of the following? #2324

I used Loco Translate to translate those strings.

**Comment by eri-trabiccolo** [comment] 2023-06-12 10:16
> I used Loco Translate to translate those strings.

But that doesn't relate the issue to Loco Translate...
You agree on that, right?

You could reproduce it by switching the user language to whatever language different than the site language.
Right?

**Comment by dominiquemariano** [comment] 2023-06-12 10:16
> How this is related to Loco Translate?
> 
> Is this a duplicate of the following? #2324

Looks like it is a duplicate.

**Comment by eri-trabiccolo** [comment] 2023-06-12 10:19
If it's a duplicate then https://github.com/gocodebox/lifterlms/pull/2326/ should fix it
close as duplicate of #2324

**Closed as completed** 2023-06-12 10:19 UTC
