### ISSUE TITLE
Inconsistent behavior with Auto Saving while using Course Builder.

### ISSUE THREAD

**Issue by actuallyakash** [gocodebox/lifterlms#2521] opened 2023-09-08 10:37 UTC
### Reproduction Steps

1. Launch Course Builder.
2. And make some general changes.

### Expected Behavior

1. The Save button should save the changes directly after making changes.
2. Or should take around less than 2 seconds to save changes.
3. Or should enable the save button after detecting the user has made some changes.

### Actual Behavior

1. The save button doesn't get enabled even after making changes. It enables in a random order and takes too much time leaving the user in anticipation.
2. The waiting time for the Save button to get enabled is random and can't be predicted.
3. Sometimes it doesn't get enabled at all even after making changes which results in data loss due to page reload.
4. After making changes, the auto-save shows the button in the "**Saved**" state and when we leave the page it shows the leave page confirmation box. It means if I leave the page, all the changes will vanish and if I don't and want to save it, I can't because the Save button is disabled and it's still in the "Saved" state.

This issue has been recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

**Comment by actuallyakash** [comment] 2023-09-08 10:39
The alternative is:

To enable the button quickly after making changes, just reload the page and deny the Leave Page confirmation box. the button will get enabled.

**Comment by eri-trabiccolo** [comment] 2023-09-28 07:35
About the actual behavior:

>  The save button doesn't get enabled even after making changes. It enables in a random order and takes too much time leaving the user in anticipation.

This seems a bug. Can you reproduce it consistently? Like change only one thing and see whether or not the save button gets enabled.

>    The waiting time for the Save button to get enabled is random and can't be predicted.

Actually it's not random and can be predicted, the check on whether the save button needs to be enabled is run every 10 seconds, this value can be modified using this filter: https://github.com/gocodebox/lifterlms/blob/185e02878c7395e795b3763a501f645ea39bc8d7/includes/admin/class.llms.admin.builder.php#L645C9-L645C35

>    Sometimes it doesn't get enabled at all even after making changes which results in data loss due to page reload.

This is very related to the point one, we need to find a pattern, is there a specific input that when changed is not detected as such?

 >  After making changes, the auto-save shows the button in the "Saved" state and when we leave the page it shows the leave page confirmation box. It means if I leave the page, all the changes will vanish and if I don't and want to save it, I can't because the Save button is disabled and it's still in the "Saved" state.

I cannot reproduce this, you're saying that when the "confirmation box" shows up, if you click on "Stay on page", then the Save Button doesn't get enabled? The confirmation box shows up when an unsaved change is detected, and when that happens the button state is changed accordingly:
https://github.com/gocodebox/lifterlms/blob/185e02878c7395e795b3763a501f645ea39bc8d7/assets/js/builder/Controllers/Sync.js#L43
https://github.com/gocodebox/lifterlms/blob/185e02878c7395e795b3763a501f645ea39bc8d7/assets/js/builder/Controllers/Sync.js#L46
https://github.com/gocodebox/lifterlms/blob/185e02878c7395e795b3763a501f645ea39bc8d7/assets/js/builder/Controllers/Sync.js#L109
https://github.com/gocodebox/lifterlms/blob/185e02878c7395e795b3763a501f645ea39bc8d7/assets/js/builder/Views/Sidebar.js#L97
https://github.com/gocodebox/lifterlms/blob/185e02878c7395e795b3763a501f645ea39bc8d7/assets/js/builder/Views/Sidebar.js#L170

Is it possible that after you clicked on "Stay on page" the button, accidentally the autosave was triggered and then the button rapidly went from _disabled_ to _enabled_ to _disabled_ state again? So everything was saved but it was not clear?

**Comment by eri-trabiccolo** [comment] 2023-10-16 10:08
@actuallyakash 
when you got time, a feedback on my reply?

**Comment by actuallyakash** [comment] 2023-10-16 17:24
> About the actual behaviour:

> > The save button doesn't get enabled even after making changes. It enables in a random order and takes too much time leaving the user in anticipation.

> This seems like a bug. Can you reproduce it consistently? Like change only one thing and see whether or not the save button gets enabled.

Yeah, I can reproduce it consistently. Below are some experiments:

1. Updated Lesson Title - Took 19.54 seconds - to save automatically.
2. Updated Quiz Title     - Took 27.90 seconds - to enable save button.
3. Enable Limit Attempts - Took 12.79 seconds - to enable save button.
4. Enable Question Banks - Took 5.29 seconds - to enable save button.

It seems to work fine for now. I'm not able to reproduce the case when it was not getting enabled at all.

> > The waiting time for the Save button to get enabled is random and can't be predicted.

> Actually it's not random and can be predicted, the check on whether the save button needs to be enabled is run every 10 seconds, this value can be modified using this filter: https://github.com/gocodebox/lifterlms/blob/185e02878c7395e795b3763a501f645ea39bc8d7/includes/admin/class.llms.admin.builder.php#L645C9-L645C35

Oh, maybe it's due to the local server being slow. When testing now it seems to enable the save button quite fast.

> > Sometimes it doesn't get enabled at all even after making changes which results in data loss due to page reload.

> This is very related to the point one, we need to find a pattern, is there a specific input that when changed is not detected as such?

Let's keep this issue open for some time and once I'll get that particular pattern, I'll post it here. It seems to work fine most of the time right now. However, I mostly faced issues with the save button while working on quizzes.

> > After making changes, the auto-save shows the button in the "Saved" state and when we leave the page it shows the leave page confirmation box. It means if I leave the page, all the changes will vanish and if I don't and want to save it, I can't because the Save button is disabled and it's still in the "Saved" state.

> I cannot reproduce this, you're saying that when the "confirmation box" shows up, if you click on "Stay on page", then the Save Button doesn't get enabled? The confirmation box shows up when an unsaved change is detected, and when that happens the button state is changed accordingly:

It happened on a customer's website that it was not getting enabled at all. There were no caching plugins.
Also, it happened on my local installation once while working on the question banks, although, it's working fine for now.

> Is it possible that after you clicked on "Stay on page" the button, accidentally the autosave was triggered and then the button rapidly went from disabled to enabled to disabled state again? So everything was saved but it was not clear?

I didn't face this case, as after clicking "Stay on page", the button didn't change at all and when I clicked reload the changes I made were not there. Again, I'm not able to reproduce the issue.

**Comment by dominiquemariano** [comment] 2024-02-12 11:37
Another ticket complaining about this is HS-238541. Should we always have the "Save" button in the course builder to be **always clickable**?

**Comment by dominiquemariano** [comment] 2024-02-19 12:59
Another ticket complaining is HS-238793.

**Comment by brianhogg** [comment] 2024-03-01 16:36
The saving check happens every 10 seconds, so it's random when it'll happen. The title was not editable but that is being fixed separately.

@dominiquemariano It's worth recommending that users disable auto save in their profile if they're having issues. With the course builder UX/UI changes the save button should appear within 1 second with auto save disabled vs. up to 10 seconds.

I'm going to close this issue for now as it has a few different paths in it (ie. consistency of saves, time to show save button which is being changed, un-reproducable showing of "stay on page" message, etc). We can create one issue per re-producable bug we see and tackle them one-by-one.

**Closed as completed by brianhogg** 2024-03-01 16:36 UTC
Labels: Type: Enhancement, Status: Need Information, Severity: Normal, Status: Has Alternative
