### ISSUE TITLE
Instructor reports

### ISSUE THREAD

**Issue by inokesh** [gocodebox/lifterlms#873] opened 2019-05-29 06:08 UTC
**I.** At the moment I'm seeing a problem - the data in the reports for instructors are not displayed correctly. Instructor courses, enrolled Students, assignments have no information. The quizzes table shows all quizzes, not just those where the instructor is the author.

Access to the test platform (Fresh install, only add courses/instructors/students):
[amber-goose.w6.wpsandbox.pro](http://amber-goose.w6.wpsandbox.pro/)
Login: instructor1; instructor2
Password: 12345

Each of the instructors has one course and one enrolled student, when entering the reports, only the data in the quizzes tab is displayed.

**II.** Also, there is a problem with sending messages by an instructor in the Private Area. The message "Unable to save comment. Please try again" On the test platform (amber-goose) there is no possibility to reproduce, because there is a problem with access to the zone itself (404 error) for the administrator and instructors.

**III.** I also have a problem with adding custom information to tables. I [use this guide](https://lifterlms.com/docs/adding-custom-columns-reporting-tables-export-files/) to add information. But the only thing that happens is to add the name of the column and its duplication to the content.

[Example code](http://dl4.joxi.net/drive/2019/05/24/0028/2950/1842054/54/b414c704a6.jpg) | What the information [in the report looks like](http://dl3.joxi.net/drive/2019/05/24/0028/2950/1842054/54/efab9563f3.jpg)

The working tables look like this:

[Code](http://dl4.joxi.net/drive/2019/05/24/0028/2950/1842054/54/a2f28d450c.jpg) | [Table](<http://dl4.joxi.net/drive/2019/05/24/0028/2950/1842054/54/99b673b21f.jpg>)

This problem is observed in the following tables:

- llms.table.courses
- llms.table.memberships
- llms.table.quiz.attempts
- class-llms-table-assignments
- class-llms-table-assignments-submissions

I think the problem is with this code. The code of [working tables looks like this](http://dl4.joxi.net/drive/2019/05/17/0028/2950/1842054/54/0e628ed90a.jpg)

The dysfunctional, [right this](http://dl4.joxi.net/drive/2019/05/17/0028/2950/1842054/54/c94764e229.jpg)

**IV**. Also, I want to give feedback to improve the product:

A) Add the ability to view courses and lessons without restrictions only for those in which the instructor is the author. (On the frontend and backend) Now, if you add the instructor role to Unrestricted Preview Access, he can view all courses on the frontend.

B) Remove the possibility of viewing financial information for instructors. Now the [instructors can see some of the course data](http://dl3.joxi.net/drive/2019/05/24/0028/2950/1842054/54/c77fb7c226.jpg)

C) Remove access to students' contact information (phone numbers, addresses, emails) from instructors. To ensure that all interaction takes place only on the website.

D) Restrictions on the capabilities of Guttenberg and Course Builder. (Remove the reorder and editing of LifterLMS blocks. Ability to edit only text and media materials.)

I know that some of these items can be implemented by changing the template/filtration/adding css rules on my side, which I did. But I think this would be useful for all customers by default.

 

Thank you for the excellent system and your work!

**Comment by eri-trabiccolo** [comment] 2019-06-07 18:18
Hi @inokesh,
many thanks for your appreciation and sorry for the late reply.

Thanks for this detailed report!
Let me go throughout your points:

> **I.** At the moment I'm seeing a problem - the data in the reports for instructors are not displayed correctly. Instructor courses, enrolled Students, assignments have no information. The quizzes table shows all quizzes, not just those where the instructor is the author.
> 
> Access to the test platform (Fresh install, only add courses/instructors/students):
> [amber-goose.w6.wpsandbox.pro](http://amber-goose.w6.wpsandbox.pro/)
> Login: instructor1; instructor2
> Password: 12345
> 
> Each of the instructors has one course and one enrolled student, when entering the reports, only the data in the quizzes tab is displayed.

I can see the issue on the test platform, though I'm not able to reproduce it on my local install :/ 
I'm going to further investigate into this!
Meantime the fact that the only available data are on the quizzes tab and that all the courses quizzes are displayed suggests (also) a bug in that reporting screen: an instructor should see only quizzes of his own courses there. I've opened a specific issue for the quizzes here -> https://github.com/gocodebox/lifterlms/issues/879

> **II.** Also, there is a problem with sending messages by an instructor in the Private Area. The message "Unable to save comment. Please try again" On the test platform (amber-goose) there is no possibility to reproduce, because there is a problem with access to the zone itself (404 error) for the administrator and instructors.

I don't seem to be able to reproduce this issue. Could you please provide me with the exact steps i should follow in order to reproduce it? Thanks!


> **III.** I also have a problem with adding custom information to tables. I [use this guide](https://lifterlms.com/docs/adding-custom-columns-reporting-tables-export-files/) to add information. But the only thing that happens is to add the name of the column and its duplication to the content.
> 
> [Example code](http://dl4.joxi.net/drive/2019/05/24/0028/2950/1842054/54/b414c704a6.jpg) | What the information [in the report looks like](http://dl3.joxi.net/drive/2019/05/24/0028/2950/1842054/54/efab9563f3.jpg)
> 
> The working tables look like this:
> 
> [Code](http://dl4.joxi.net/drive/2019/05/24/0028/2950/1842054/54/a2f28d450c.jpg) | [Table](http://dl4.joxi.net/drive/2019/05/24/0028/2950/1842054/54/99b673b21f.jpg)
> 
> This problem is observed in the following tables:
> 
> * llms.table.courses
> * llms.table.memberships
> * llms.table.quiz.attempts
> * class-llms-table-assignments
> * class-llms-table-assignments-submissions
> 
> I think the problem is with this code. The code of [working tables looks like this](http://dl4.joxi.net/drive/2019/05/17/0028/2950/1842054/54/0e628ed90a.jpg)
> 
> The dysfunctional, [right this](http://dl4.joxi.net/drive/2019/05/17/0028/2950/1842054/54/c94764e229.jpg)

Many thanks for reporting this and for your investigation throughout the code, I think you're right.
I've opened a specific issue here so that with the rest of the team we can discuss on whether or not this is by design -> https://github.com/gocodebox/lifterlms/issues/880.

I reply to the following improvement suggestions with just my opinion, other members of the team might think differently :(

> **IV**. Also, I want to give feedback to improve the product:
> 
> A) Add the ability to view courses and lessons without restrictions only for those in which the instructor is the author. (On the frontend and backend) Now, if you add the instructor role to Unrestricted Preview Access, he can view all courses on the frontend.

Not sure about this, isn't that the meaning of that option?

> B) Remove the possibility of viewing financial information for instructors. Now the [instructors can see some of the course data](http://dl3.joxi.net/drive/2019/05/24/0028/2950/1842054/54/c77fb7c226.jpg)

I think that an instructor has rights to access to the number of people that bought "his" course in a given range of time (e.g. today), why not. Also the instructor being the author of a course can also set, hence define, the access plans for that course...

> C) Remove access to students' contact information (phone numbers, addresses, emails) from instructors. To ensure that all interaction takes place only on the website.
> D) Restrictions on the capabilities of Guttenberg and Course Builder. (Remove the reorder and editing of LifterLMS blocks. Ability to edit only text and media materials.)

I see both of your points above and I can theoretically agree on them, but, as said above, in my opinion the instructor role is something a little bit different than what you're expecting it to be, since the instructor can create access plans I think that some "administrative" and editing capabilities are assigned to it by design.

> I know that some of these items can be implemented by changing the template/filtration/adding css rules on my side, which I did. But I think this would be useful for all customers by default.
> 
> Thank you for the excellent system and your work!


Thanks again for this feedback!

Cheers.

**Comment by inokesh** [comment] 2019-06-08 09:55
Hey, @eri-trabiccolo! Thanks for your answer and all the explanations!

> Also, there is a problem with sending messages by an instructor in the Private Area. The message "Unable to save comment. Please try again" On the test platform (amber-goose) there is no possibility to reproduce, because there is a problem with access to the zone itself (404 error) for the administrator and instructors.
>>  I don't seem to be able to reproduce this issue. Could you please provide me with the exact steps i should follow in order to reproduce it? Thanks!

Maybe the problem was on my side. If I can reproduce it on a test platform, I will write about it here. Sorry to bother you :)

> A) Add the ability to view courses and lessons without restrictions only for those in which the instructor is the author. (On the frontend and backend) Now, if you add the instructor role to Unrestricted Preview Access, he can view all courses on the frontend.
> > Not sure about this, isn't that the meaning of that option?

I wasn't quite correct. I would like the instructor to have access only to his own courses/lessons/quiz and assignment without restrictions and without this option. At this point, if you don't add his role to this option, he can't view his lessons on the front end and comment on it there. All instructor interactions take place only through the backend (wp-admin) without this option - "Unrestricted Preview Access".

Thank you again!

**Comment by eri-trabiccolo** [comment] 2019-06-10 14:33
Ah, I now I see what you mean. Thanks for the clarification!

:D

**Comment by actual-saurabh** [comment] 2019-06-10 16:57
@inokesh This is a fairly large post and for usability, each issue should be created separately with details. @eri-trabiccolo has already broken a few of the issues down into separate ones.

I'd request you to post feedback/suggestions for reporting (still in beta) on the appropriate channel here: https://lifterlms.com/docs/lifterlms-reporting-beta/ We're aware of permission issues but haven't been able to prioritise these yet: #401.

We've been collecting a lot of feedback and suggestions for reporting and have been consolidating everything to potentially revamp reporting in a future version. There's a lot of work going on in the background with respect to tracking (which feeds reporting) and as we make such changes, you'll automatically see improvements in reporting. See #636 

With respect to issues with Private Areas, I'd request you to open a support ticket on https://lifterlms.com/my-account/my-tickets/ so that we can log, track and fix those properly.

I'm going to close this issue as of now but would request you to

- log each issue separately using the appropriate issue templates (so that it's easier to make sense of and work on).
- if you're not sure about how and why to do that, create a support request using https://lifterlms.com/my-account/my-tickets/. The development team would be able to log them usefully from there.

In general, this platform/channel is reserved for really specific things and it would make it easier for everyone if it stays so. I hope I'm not coming across as rude and discouraging and I hope what I'm saying makes sense.

Thanks!

**Closed by actual-saurabh** 2019-06-10 16:57 UTC
