### ISSUE TITLE
Quiz question saved with missing information

### ISSUE THREAD

**Issue by Mte90** [gocodebox/lifterlms#736] opened 2019-01-11 14:52 UTC
### 1. Reproduction Steps

+ Editing a course and open the editing of a quiz

### 2. Expected Behavior

+ loading

### 3. Actual Behavior

![screenshot_20190111_155000](https://user-images.githubusercontent.com/403283/51040828-c4b6f080-15b8-11e9-9bd1-9cd61b3714ac.png)
Loading loop with no interaction and error in the browser

Also the users are complaining that this column is too tiny (280px) in a 16:9 screen is very few.

**Comment by thomasplevy** [comment] 2019-01-11 16:36
@Mte90 please post a copy of your system report and export the course in question and attach a copy of the course so i can recreate and review

Thanks

**Comment by thomasplevy** [comment] 2019-01-11 17:19
@Mte90 export the course: https://lifterlms.com/docs/exporting-lifterlms-courses/

We don't have a way to export import/export parts of courses (yet)

**Comment by Mte90** [comment] 2019-01-11 17:24
I sent to you by email :-)

**Comment by thomasplevy** [comment] 2019-01-11 17:35
@Mte90 

From the export

```json
              {
                "choices": [],
                "clarifications": "",
                "clarifications_enabled": "no",
                "content": "",
                "description_enabled": "no",
                "id": 2526,
                "image": [],
                "menu_order": 10,
                "multi_choices": "no",
                "name": "i",
                "parent_id": 306,
                "permalink": "https://***/llms_domanda/i/",
                "points": 0,
                "question": "",
                "question_type": "",
                "title": "I",
                "type": "llms_question",
                "video_enabled": "no",
                "video_src": ""
              },
```

Looks like the result of some corrupted data. Any idea how this question got into the quiz without any information?

The error itself is stemming from the question not having any `question_type` set. We'll have to add a check to prevent the error from displaying but the real question or issue is why is this in the database at all. If you could help me with any steps I could take to figure out how a question could get saved without any information like this that'd be really helpful.

To fix this immediately you could head into your DB and look up the `llms_question` in the `wp_posts` table and delete it. The ID is `2526`.

I'm sure you will be cautious editing from your DB directly!

If you can help with any other information about how the question got there I'll pursue further.

**Comment by thomasplevy** [comment] 2019-01-11 17:37
Maybe it's supposed to a be a true_false or choice question... Check the `wp_postmeta` table to see if theres other data that wasn't pulled into the export due to it missing it's `question_type` attribute. If it is you could add an `_llms_question_type` record to the `wp_postmeta` table to "restore" it to the quiz so it'll work properly instead of deleting it outright

**Comment by Mte90** [comment] 2019-01-11 17:39
I have no idea why it is happened, our customer (also of lifter pro) was using and reported that issue.
In the meantime I will fix by db as you suggested (carefully) and see if happen again.

**Comment by thomasplevy** [comment] 2019-01-11 17:43
@Mte90 understood. Thanks for reporting the issue. I haven't seen this kind of thing before so I'm not really certain how it happened. I'll try to figure out how to reproduce when I get some time but keep me posted if anything comes up.

**Comment by Mte90** [comment] 2019-01-11 17:48
I am not sure about what is the line that I have to remove or what is the db table to look on, because I Cannot find that id.

**Comment by thomasplevy** [comment] 2019-01-11 19:12
Can you run and reply with the output of these two queries:

```sql
SELECT * FROM wp_posts WHERE ID = 2526;
SELECT * FROM wp_postmeta WHERE post_id = 2526;
```

Modify the table prefixes if your WP install has a different db prefix than the standard.

Thanks

**Comment by Mte90** [comment] 2019-01-14 17:52
phpmyadmin say that this queries return 0 and the problem still persist.
maybe the id with issue is another one?

**Comment by thomasplevy** [comment] 2019-01-14 19:10
A quiz pulls question data into a quiz based on this query: https://github.com/gocodebox/lifterlms/blob/master/includes/class.llms.question.manager.php#L145-L172

It's a standard `WP_Query` looking for `llms_question` post types. It the question post doesn't exist in your database it should not be displaying in the array of quiz data when polled to populate the builder...

It's conceivable that the query has been unintentionally modified with a filter of some kind.

Can you try disabling any custom code, plugins, etc... that may affect `WP_Query` or default LifterLMS behavior?

**Comment by Mte90** [comment] 2019-01-15 18:49
And as usual I was working on the wrong database -.-'
I removed that post type created like a month ago.
Anyway the proble still persist after removing that post type.
There is a way that I can change the javascript and find what is the element that crash the page?

**Comment by thomasplevy** [comment] 2019-01-15 19:16
@Mte90,

Can you double check that the post has actually been removed please? Please triple check you're in the right database and if it persists please send me the updated course export file so I can check it again.

If you look through the code of the function that queries the data if the post isn't in the database it won't be loaded. That post is what's causing the error. I promise.

I don't have a way to provide you code to change in the Javascript... I mean, I guess I could solve this with JS but it gets a lot more complicated to solve. Removing the "broken" post is the solution. Can you just double/triple check it's removed... Maybe there's some object caching on your server causing it to still load despite it having been removed from the DB?

**Comment by Mte90** [comment] 2019-01-16 14:02
I sent to you another export, I checked on it and that id is not avalaible on that.
Maybe there are other data corrupted somewhere.

**Comment by thomasplevy** [comment] 2019-01-16 18:37
@Mte90 I haven't gotten any new export files. Does your customer have access to our ticketing system at https://lifterlms.com/my-account/my-tickets?

If so, please submit a ticket with regards to this issue so we can share credentials and I can look a little deeper into the specifics of this. Since I'm struggling to recreate the issue I think handling this as a support tickets as opposed to a bug report in GitHub is the best way to proceed.


Thanks,

**Comment by thomasplevy** [comment] 2019-02-05 17:08
JS error was related to custom code in child theme. Not sure about the missing data in the export. Closing because we can't recreate but if there's any more helpful details we'll reopen.

**Closed by thomasplevy** 2019-02-05 17:08 UTC
Labels: help wanted, language: js, status: can't recreate, type: bug
