### ISSUE TITLE
LifterLMS Shortcodes from Dropdown don't render in emails

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#2070] opened 2022-03-18 15:45 UTC
### Reproduction Steps

+ HS-189435
+ Create a custom email
+ from the mergecode menu copy a shortcode like [llms-user user-email] into the email
+ trigger the email to be sent

### Expected Behavior

+ the shortcode either shouldn't be in the merge code list or should render in the email

### Actual Behavior

+ the shortcode is an option in the merge codes and doesn't render in the email

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: https://natalie-test-site.myliftersite.com
Site Url: https://natalie-test-site.myliftersite.com
Login Url: https://natalie-test-site.myliftersite.com/wp-login.php
Version: 5.9.2
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Homepage (#1398) [https://natalie-test-site.myliftersite.com/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.0.0
Db Version: 6.0.0
Course Catalog: Course Catalog (#35) [https://natalie-test-site.myliftersite.com/courses/]
Membership Catalog: Membership Catalog (#36) [https://natalie-test-site.myliftersite.com/memberships/]
Student Dashboard: Dashboard (#38) [https://natalie-test-site.myliftersite.com/dashboard/]
Checkout Page: Checkout (#715) [https://natalie-test-site.myliftersite.com/checkout/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: yes
Terms Page: Activate (#443) [https://natalie-test-site.myliftersite.com/activate/]
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: yes
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: team+sandbox@lifterlms.com
Email From Name: A LifterLMS Sandbox
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 1123
Cert Bg Height: 794
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Enabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.37
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 8.0.16
Software: Apache/2.4.52 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36


Theme
-------------------------------------------

Name: Astra
Version: 3.7.9
Themeuri: https://wpastra.com/
Authoruri: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
Template: 
Child Theme: No
Llms Support: Yes


Plugins
-------------------------------------------

LifterLMS: 6.0.0
LifterLMS WooCommerce: 2.2.2
Loco Translate: 2.6.1
User Switching: 1.5.8
WooCommerce: 6.3.1
WooCommerce Subscriptions: 4.0.2
WP Mail Logging: 1.10.4
WP Rollback: 1.7.1


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No
WooCommerce: Yes


Template Overrides
-------------------------------------------




```

</details>

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [ ] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

**Comment by thomasplevy** [comment] 2022-03-18 15:50
I briefly looked into this when someone reported it on slack yesterday and I'm pretty sure this is an oversight in 6.x where the merge codes were added but never tested.

The shortcodes need special handling to work when they're fired during a background process like with certificates here: 
https://github.com/gocodebox/lifterlms/blob/0a5e0a2c7cd522074f1988dd0979e3aa6289a0c3/includes/models/model.llms.user.certificate.php#L713-L715)

The same should be applied to emails but I don't believe this was ever done. Likely it was on my mental todo backlog and I forgot about it during the release and we never noticed the introduction of a new email feature that doesn't work.

**Comment by thomasplevy** [comment] 2022-03-21 22:00
Hey @nrherron92 did you confirm this yourself? I looked at this really quickly when someone reported it on slack but my memory (and quick research) proved to be incorrect.

Here's the relevant code: https://github.com/gocodebox/lifterlms/blob/0a5e0a2c7cd522074f1988dd0979e3aa6289a0c3/includes/emails/class.llms.email.engagement.php#L115-L132

I'm now actually even remembering that you and I talked about this around the release of v1 and I added this based on your feedback!

In any event... I just ran some tests after reviewing the code and it is in fact working as I'd expect it to.

Could you request some additional information from the user reporting the issue, namely around environment, system report, specific content being used in the email, and etc... so we can investigate further.

As of this moment I can't recreate based on the information the user provided, which was "It doesn't work"

**Comment by nrherron92** [comment] 2022-03-22 13:51
@thomasplevy I did test it but very briefly and was able to recreate it when I used the email shortcode (by recreate "it" I mean the email address shortcode does not display the email address on the email when sent).

However, it seems to _only_ apply to the email address shortcode. The others work fine: 
<img width="587" alt="image" src="https://user-images.githubusercontent.com/47434271/159497035-301e06bc-f662-43dc-a5cc-197d773fdba6.png">

I'll reach out to the user and see if this is his experience as well! --- Actually, I just opened the ticket again and he has only said what I confirmed. that the email address shortcode won't populate (though, the workaround surely is to use the email merge code?! -- I'll test if this works quickly but I don't see why it wouldn't )

**Comment by nrherron92** [comment] 2022-03-23 17:25
HS-189642

![image](https://user-images.githubusercontent.com/47434271/159759314-63ca266f-1365-4120-9473-b1464e9d5c8e.png)

**Comment by thomasplevy** [comment] 2022-03-23 18:16
@nrherron92 can you let me know if this is an engagement email or a notification? I've been testing engagement emails. These shortcodes don't show in notification emails. But I want to be certain because I'm unable to reproduce any of the issues you (or the users) are encountering...

**Comment by nrherron92** [comment] 2022-03-23 18:18
@thomasplevy they are engagement emails (I think I mentioned notifications a second ago but I am just bad at reading Finnish! she is using engagement emails as well!)

**Comment by thomasplevy** [comment] 2022-04-01 18:25
@gocodebox/engineering what am I missing here that I can't recreate?

**Comment by pondermatic** [comment] 2022-04-01 19:15
Here are the steps I performed. It works for me.
1. In the WordPress admin menu, go to Engagements -> Emails.
2. Click the "Add Email Template" button.
3. Set the title.
4. Click the "Merge Codes" button above the email content area.
5. Select "Email Address" or "Student Email Address". `[llms-user user_email]` or `{email_address}` is inserted into the email content text area. Both work for me.
6. Set email subject.
7. Set email heading.
8. I left the email to be the default `{student_email}} value.
9. Navigate to Engagements in the WordPress admin menu.
10. Click the "Add Engagement" button.
11. Set the title
12. Set triggering event to "Student enrolls in a course".
13. Select a course.
14. Set engagement type to "Send an Email".
15. Select the engagement created earlier.
16. Edit the course that was selected earlier and enroll a user.

**Comment by pondermatic** [comment] 2022-04-01 19:36
I also tested with all of the `[llms-user X]` shortcodes and all worked.

**Comment by thomasplevy** [comment] 2022-04-01 19:37
@pondermatic just to be clear you're saying you're able to recreate with this steps or it's "working" (you also can't recreate)?

**Comment by thomasplevy** [comment] 2022-04-01 19:38
I see your last comment now and you're probably saying it is working (you can't recreate)

**Comment by pondermatic** [comment] 2022-04-01 19:40
It works on my site. I'm checking out their site now.

**Comment by pondermatic** [comment] 2022-04-01 20:33
I don't see anything on their site that is obviously the culprit. If this were a staging site, we could try turning off most of the plugins. Maybe one of them is using the WordPress [`remove_all_shortcodes()`](https://github.com/WordPress/wordpress-develop/blob/5.9.2/src/wp-includes/shortcodes.php#L118) function?

I did not set up an account to test the email. Is it OK if I do?

**Comment by thomasplevy** [comment] 2022-04-01 20:40
@nrherron92 where did you recreate this? it'd be better to test on a stage rather than in production

**Comment by nrherron92** [comment] 2022-04-04 16:21
@thomasplevy @pondermatic 

Okay I think I found out what's going on here.

The key thing is it has to be a brand new user whose information hasn't been saved before. 

If you use an account that already has the email/billing address/ username etc. all saved the information will show up as expected.

However, when you register a brand new user it isn't finding the information so the shortcode shows up instead of the user's information.

I can recreate this on a local site. you can use myliftersite too, but you just have to add the mail checker to it to see.

**Comment by pondermatic** [comment] 2022-04-11 17:39
@nrherron92, I'm still not able to recreate this issue on my local site. The `[llms-user user_email]` shortcode is replaced by the brand new user's email address.

Do any of the LifterLMS user shortcodes work?
| Label | Shortcode  |
|-|-|
| Username | [llms-user user_login] |
| Email Address | [llms-user user_email] |
| First Name | [llms-user first_name] |
| Last Name | [llms-user last_name] |
| Display Name | [llms-user display_name] |
| Address | [llms-user llms_billing_address_1] |
| Address Line 2 | [llms-user llms_billing_address_2] |
| City | [llms-user llms_billing_city] |
| Country | [llms-user llms_billing_country] |
| State / Region | [llms-user llms_billing_state] |
| Postal / Zip Code | [llms-user llms_billing_zip] |
| Phone Number | [llms-user llms_phone] |

**Comment by nrherron92** [comment] 2022-04-11 17:53
I don't understand! I can't get any of them to work with a new user!
  
Email in gmail:
<img width="785" alt="image" src="https://user-images.githubusercontent.com/47434271/162799568-625d7884-73c4-478c-aac9-87812939d4f0.png">

Email on site set up:
![image](https://user-images.githubusercontent.com/47434271/162799215-4b88cc55-6704-424d-9d0b-43054b0344c5.png)

User info:
![image](https://user-images.githubusercontent.com/47434271/162799787-93ba29f7-0193-4f7d-8275-ebd938de17f9.png)


![image](https://user-images.githubusercontent.com/47434271/162799731-1f0a99a5-3bd2-4b2b-ae85-cf1f737777d7.png)

**Comment by pondermatic** [comment] 2022-04-11 20:08
While tracing the flow of how the email body is built, my system has suddenly stopped merging shortcodes!

**Comment by pondermatic** [comment] 2022-04-11 20:58
It turns out that the shortcodes are **not** replaced when a user enrolls using a free access plan. If they enroll with a `one-time payment` or an `every X` access plan, the shortcodes are merged. Bug confirmed.

**Comment by pondermatic** [comment] 2022-04-11 21:40
Developer notes:
"Free" Flow:
1. `LLMS_Controller_Orders::create_pending_order()`
2. `LLMS_Payment_Gateway::handle_pending_order()`
3. `LLMS_Controller_Orders::transition_status( 'completed', 'pending' )`
4. `LLMS_Controller_Orders::complete_order()`
5. `llms_enroll_student()`
6. `LLMS_Student::enroll()`
7. `LLMS_Engagements::maybe_trigger_engagement()`
8. `LLMS_Engagements::trigger_engagement()`
9. `LLMS_Engagement_Handler::handle_email()`
10. `LLMS_Email_Engagement::send()`
11. `LLMS_Email::send()`
12. `LLMS_Email::format_string()`
13. `do_shortcode()`
At this point, the global `$shortcode_tags` has 7 elements, none of them for LifterLMS.

"One-Time" Flow, changing order status from `Pending` to `Completed`.
1. `LLMS_Admin_Metabox::save_actions()`
2. `LLMS_Meta_Box_Order_Submit::save()`
3. `LLMS_Controller_Orders::transition_status( 'completed', 'pending' )`
4. `LLMS_Controller_Orders::complete_order()`
5. `llms_enroll_student()`
6. `LLMS_Student::enroll()`
 7. `LLMS_Engagements::maybe_trigger_engagement()`
8. `LLMS_Engagements::trigger_engagement()`
9. `LLMS_Engagement_Handler::handle_email()`
10. `LLMS_Email_Engagement::send()`
11. `LLMS_Email::send()`
12. `LLMS_Email::format_string()`
13. `do_shortcode()`
There are 37 elements in global `$shortcodes`, including an `llms-user` array.

**Comment by pondermatic** [comment] 2022-04-13 19:37
@nrherron92, we have found and fixed this issue. I expect it will be included in the next release.

**Closed as completed** 2022-04-19 17:29 UTC
Labels: Type: Bug, Status: Has PR, Severity: Normal
