### ISSUE TITLE
Pricing Table Block Visibility Settings Not Allowing For Members-only Visibility

### ISSUE THREAD

**Issue by magicemilymiddleton** [gocodebox/lifterlms#1785] opened 2021-09-16 21:13 UTC
### Reproduction Steps

(This was brought up in LifterLMS Office Hours)

1 - Create a course (or edit an existing course that's using the WordPress editor)
2 - Make an access plan on the course so the block will have something to show
3 - Change the visibility on the 'LifterLMS Pricing Table Block' to only be visible to someone enrolled in a specific membership.
4 - Click Update
(then you should see the visibility settings you just set up for that block revert back to 'Everyone'

Video demo (25 sec):
https://www.loom.com/share/f1f4bf6d105b4b26a0bb3bad68554c5f

<img width="1732" alt="Screen Shot 2021-09-16 at 4 10 36 PM" src="https://user-images.githubusercontent.com/76497148/133686112-05c5b903-feed-4ac7-9d1b-2b8d97772954.png">

### Expected Behavior
The visibility option for the 'Pricing Table Block' would stay as you set them before clicking update

### Actual Behavior
The visibility options revert back to 'Everyone'

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: [removed]/wp-login.php
Version: 5.8.1
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Home (#145) [[removed]/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 5.3.1
Db Version: 5.3.1
Course Catalog: Course Catalog (#14) [[removed]/courses/]
Membership Catalog: Membership Catalog (#15) [[removed]/memberships/]
Student Dashboard: Dashboard (#17) [[removed]/dashboard/]
Checkout Page: Enrollment (#16) [[removed]/enrollment/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: no
Terms Page: Not Set
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: no
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Disabled
Manual Logging: 
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.35
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 7.3.30
Software: Apache/2.4.48 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36


Theme
-------------------------------------------

Name: Twenty Twenty-One
Version: 1.4
Themeuri: https://wordpress.org/themes/twentytwentyone/
Authoruri: https://wordpress.org/
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

LifterLMS: 5.3.1


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------




```

</details>

This issue has be recreated:
+ [ ] Locally
+ [ X] On a staging site
+ [ X] On a production website
+ [ X] With only LifterLMS and a default theme

**Comment by thomasplevy** [comment] 2021-09-16 21:31
@willmiddleton-lifterlms duplicate of https://github.com/gocodebox/lifterlms-blocks/issues/46, closing in favor of that issue

**Closed as completed by thomasplevy** 2021-09-16 21:31 UTC
