### ISSUE TITLE
Password Meter Says it requires 6 characters but only works with 7 on weak

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#1421] opened 2020-11-05 21:00 UTC
### Reproduction Steps

+ Set the password strength to weak
+ Attempt a password of any combination but with only 6 characters

### Expected Behavior

+ the password remains too weak.

### Actual Behavior

+ The password remain too weak until a 7th character is added.

The workaround is just turning off the password meter entirely. 

This issue has be recreated:
+ [X] Locally
+ [X] On a staging site
+ [X] On a production website
+ [X] With only LifterLMS and a default theme

HS-2649502

**Comment by thomasplevy** [comment] 2020-11-05 21:42
@nrherron92 This gets really complicated really quick but this *is not a bug*

Password strength is *not* the same as password minimum length.

These are two different requirements that work together. It's conceivable that there *is* a combination of characters that can be used to allow for a 6 character "weak" password. I'm not going to setup a bot to test this. It's also conceivable that there isn't (of course). The 6 character limit is somewhat arbitrary but it's not a bug.

I also see the customer has stated that when using "Medium" the password must be 12 characters. Again, the numbers here are the MINIMUM REQUIRED LENGTH but that minimum is not designed to change dynamically based on the strength.

I can almost guarantee that it's impossible to create a medium or strong password that's only 6 characters long, but that minimum still stands.

The fact that this message has existed like this since 2016 without anyone reporting this as a bug leads me to believe that thes message should be customized for this user (as you've suggested in the ticket) and we can carry on.

Perhaps the message should be generally changed, I don't know. Maybe we should raise the minimum to 8 just to be safe.

I'm going to close this as it's not a bug but if anyone feels very strongly that I should be addressing this differently please reply with a good argument and solution and I'll reopen.

**Closed as completed by thomasplevy** 2020-11-05 21:42 UTC
Labels: Type: Bug, Severity: Low, Status: Has Alternative
