### ISSUE TITLE
Membership Catalog Missing Author Name

### ISSUE THREAD

**Issue by nrherron92** [gocodebox/lifterlms#897] opened 2019-07-08 20:17 UTC
### Reproduction Steps

Set authors on Memberships and save.
Open Membership Catalog Page. 
The author name will be missing from the memberships in the catalog. 
$args in function llms_get_author( $args = array() ) will come back black for user_id on Membership Catalogs.

### Expected Behavior

Should show author name for memberships

### Actual Behavior

Author name does not display

**Comment by actual-saurabh** [comment] 2019-07-11 12:29
This is due to the post type support parameter missing the author element: https://github.com/gocodebox/lifterlms/blob/88ae26c902da29e8765d2e8b29b46e635dc3b075/includes/class.llms.post-types.php#L463. Just need to add that to fix.

**Comment by actual-saurabh** [comment] 2019-07-11 12:32
https://github.com/gocodebox/lifterlms/commit/41fcdc92fa9dd873e9c1405e0f162b7214f88c72

**Comment by thomasplevy** [comment] 2020-01-07 17:08
Should memberships actually display authors/instructors?

**Comment by eri-trabiccolo** [comment] 2020-08-01 21:45
I think they shouldn't.

**Comment by thomasplevy** [comment] 2020-08-03 15:45
@eri-trabiccolo yea, I agree. Should we close this?

**Comment by eri-trabiccolo** [comment] 2020-08-03 17:03
@thomasplevy 
I need to verify what actually happens now with the block editor. I might be wrong but I remember that, unlike what happens with the classic editor, with the block editor a `post_author` is always set as the one who created the post. The `'author'` cpt support would just allow for changing it (with a "meta box").
In this case we have to explicitly return no authors for membership post types in our model (or maybe in general for cpts who don't support `'author'`.
Disclaimer: I might have false memory...

**Comment by eri-trabiccolo** [comment] 2020-08-04 13:32
@thomasplevy 
I was looking into this but, the thing is that I cannot reproduce the issue anymore.
The Membership's author is always displayed in catalogs, and since the post type doesn't suppor the author you cannot change it from the one who actually created the membership.
So... if the issue is that the membership's author is missing in memberships catalog, well that does not seem to be true anymore. 
If the issue is that now they are displayed we need to fix it.

**Comment by thomasplevy** [comment] 2020-08-04 15:34
@eri-trabiccolo current behavior is correct behavior. If we have reports of this as a big issue we can adjust later. Closing for now.

**Closed by thomasplevy** 2020-08-04 15:34 UTC
