### ISSUE TITLE
Enhancement: Fix incompatibility issue with Beaver Builder "Equalize Heights" column setting.

### ISSUE THREAD

**Issue by dominiquemariano** [gocodebox/lifterlms#2477] opened 2023-07-05 12:03 UTC
### Reproduction Steps

1. Install and activate the following plugins: **Beaver Builder Plugin (Pro Version)** and **Beaver Themer**.
2. Install and activate the following themes: **Beaver Builder Child Theme** and **Beaver Builder Theme**.
3. Go to `WordPress Dashboard > Beaver Builder > Themer Layouts > Add New`.
4. Set a title for `Title`.
6. Keep `Type` to `Themer Layout`.
7. Set `Layout` to `Singular`.
8. Click on the `Add Themer Layout` button.
9. This will load another page.
10. Set `Location` to `Lesson` and then to `All Lessons`, as you can see in [this screenshot](https://share.getcloudapp.com/8LuYbX0Q).
11. Click on the `Publish` button.
12. Once published, click on the `Launch Beaver Builder` button.
13. Set **`Preview As:`** to any lesson you have published in `WordPress Dashboard > Courses`.
14. Create a row with **two columns** on it.
15. On the column settings of the first column, set **`Equalize Heights`** to **`Yes`**.
16. On the second column, add a `Post Content` element. As you can see in [this screenshot](https://share.getcloudapp.com/X6u7em5r), this `Post Content` element will show the LifterLMS lesson navigation elements.
17. Click on the `Done` button and then click on `Publish`. This will reload the page.
18. Now preview the page in mobile/responsive view. You will see that the lesson navigation remains a fixed width and causes a layout issue, as you can see in [this screenshot](https://share.getcloudapp.com/geuPbn4L).
19. Edit the template again and set **`Equalize Heights`** to **`No`**. You will see that the lesson navigation behaves correctly as expected in mobile/responsive view, as you can see in [this screenshot](https://share.getcloudapp.com/Bluz4kKR).

### Expected Behavior
See [this screenshot](https://share.getcloudapp.com/Bluz4kKR).

### Actual Behavior
See [this screenshot](https://share.getcloudapp.com/geuPbn4L).

### Suggested Enhancement
A change in responsive layout (as shown [in this screenshot](https://share.getcloudapp.com/mXuGpwJz)) can avoid this conflict with Beaver Builder. 

### Affected Ticket
HS-219024. Note that in the customer's website, setting **`Equalize Heights`** to **`No`** for the first column in a two-column row **does not fix the problem**. However, if you visit the lessons on the front-end and remove the classes `fl-col-group` and `fl-col-group-equal-height`, as you can see in [this screenshot](https://share.getcloudapp.com/lluX5rbJ), fixes the conflict with LifterLMS.

This issue has been recreated:
+ [x] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [ ] With only LifterLMS and a default theme

**Comment by eri-trabiccolo** [comment] 2023-07-06 13:51
There's nothing to do on our side, it's not related to LifterLMS, it can happen with just whatever:
The problem is that max-width:400px on that element, which is not a LifterLMS element, but a BeaverBuilder one.
![Schermata 2023-07-06 alle 15 45 31](https://github.com/gocodebox/lifterlms/assets/7689242/19d33f1d-4651-4af0-9eeb-3194a504a834)

Makes no sense when the window's width goes below 400px (a bit more actually)

This is not an issue on our side, and you've already provided the user with some CSS code to overcome the issue.

Closing this.

**Closed as completed by eri-trabiccolo** 2023-07-06 13:51 UTC
Labels: invalid, Status: Has Alternative
